-- ===== app_user @ supabase/migrations/00000000000000_baseline.sql:24 =====
CREATE TABLE IF NOT EXISTS public.app_user ( user_id uuid NOT NULL, woreda_id uuid, role text NOT NULL, full_name text NOT NULL, username text NOT NULL, status text DEFAULT 'active'::text NOT NULL, last_login_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, invited_by_user_id uuid, invited_at timestamp with time zone );

-- ===== approval @ supabase/migrations/00000000000048_task11_schema_gaps.sql:260 =====
CREATE TABLE IF NOT EXISTS public.approval ( approval_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, entity text NOT NULL, entity_id uuid NOT NULL, approver_user_id uuid, decision text NOT NULL, decision_at timestamp with time zone DEFAULT now() NOT NULL, stage_no integer NOT NULL, reason text, CONSTRAINT approval_pkey PRIMARY KEY (approval_id), CONSTRAINT approval_decision_check CHECK (decision IN ('approved', 'rejected', 'returned')) );

-- ===== arrears_installment_charge @ supabase/migrations/00000000000080_rental_phase4_arrears.sql:419 =====
CREATE TABLE IF NOT EXISTS public.arrears_installment_charge ( mapping_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), installment_id uuid NOT NULL REFERENCES public.arrears_repayment_installment(installment_id), rent_charge_id uuid NOT NULL REFERENCES public.rent_charge(rent_charge_id), charge_amount_snapshot numeric(14, 2) NOT NULL CHECK (charge_amount_snapshot > 0), charge_amount_snapshot_enc bytea, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'cancelled')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (installment_id, rent_charge_id) );

-- ===== arrears_plan_sequence @ supabase/migrations/00000000000080_rental_phase4_arrears.sql:182 =====
CREATE TABLE IF NOT EXISTS public.arrears_plan_sequence ( woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), seq_year smallint NOT NULL, last_value integer NOT NULL DEFAULT 0, PRIMARY KEY (woreda_id, seq_year) );

-- ===== arrears_repayment_installment @ supabase/migrations/00000000000080_rental_phase4_arrears.sql:356 =====
CREATE TABLE IF NOT EXISTS public.arrears_repayment_installment ( installment_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), plan_id uuid NOT NULL REFERENCES public.arrears_repayment_plan(plan_id), installment_number integer NOT NULL CHECK (installment_number >= 1), due_date date NOT NULL, amount numeric(14, 2) NOT NULL CHECK (amount > 0), amount_enc bytea, status text NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'due', 'paid', 'overdue', 'cancelled')), settled_by_payment_id uuid REFERENCES public.rental_payment(payment_id), settled_at timestamptz, UNIQUE (plan_id, installment_number) );

-- ===== arrears_repayment_plan @ supabase/migrations/00000000000080_rental_phase4_arrears.sql:195 =====
CREATE TABLE IF NOT EXISTS public.arrears_repayment_plan ( plan_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid NOT NULL REFERENCES public.rent_account(rent_account_id), resident_id uuid NOT NULL REFERENCES public.resident(resident_id), plan_number text NOT NULL, original_arrears_amount numeric(14, 2) NOT NULL CHECK (original_arrears_amount > 0), original_arrears_amount_enc bytea, assigned_arrears_amount numeric(14, 2) NOT NULL CHECK (assigned_arrears_amount > 0), assigned_arrears_amount_enc bytea, installment_count integer NOT NULL CHECK (installment_count >= 1), status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'under_review', 'returned', 'approved', 'active', 'completed', 'defaulted', 'cancelled')), reason text, return_reason text, requested_by_user_id uuid REFERENCES public.app_user(user_id), approved_by_user_id uuid REFERENCES public.app_user(user_id), approval_decision_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (woreda_id, plan_number) );

-- ===== attachment @ supabase/migrations/00000000000048_task11_schema_gaps.sql:306 =====
CREATE TABLE IF NOT EXISTS public.attachment ( attachment_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, entity text NOT NULL, entity_id uuid NOT NULL, file_name text NOT NULL, mime text NOT NULL, size_bytes integer NOT NULL, checksum text NOT NULL, storage_path text NOT NULL, uploaded_by uuid, uploaded_at timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT attachment_pkey PRIMARY KEY (attachment_id) );

-- ===== audit_log @ supabase/migrations/00000000000000_baseline.sql:37 =====
CREATE TABLE IF NOT EXISTS public.audit_log ( audit_log_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid, actor_user_id uuid, entity_name text NOT NULL, entity_id text, action_type text NOT NULL, old_value_json jsonb, new_value_json jsonb, action_at timestamp with time zone DEFAULT now() NOT NULL, source_ip text );

-- ===== console_role @ supabase/migrations/00000000000009_console_roles.sql:15 =====
CREATE TABLE public.console_role ( console_role_id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, name text NOT NULL UNIQUE, description text, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid REFERENCES public.app_user(user_id) );

-- ===== console_role_permission @ supabase/migrations/00000000000009_console_roles.sql:33 =====
CREATE TABLE public.console_role_permission ( console_role_id uuid NOT NULL REFERENCES public.console_role(console_role_id) ON DELETE CASCADE, permission_key text NOT NULL, is_granted boolean DEFAULT false NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, PRIMARY KEY (console_role_id, permission_key), CONSTRAINT console_role_permission_key_check CHECK (permission_key = ANY (ARRAY[ 'console.tenants.manage', 'console.users.manage', 'console.audit.view', 'console.credential_template.manage', 'console.console_users.manage' ]::text[])) );

-- ===== credential_number_sequence @ supabase/migrations/00000000000000_baseline.sql:49 =====
CREATE TABLE IF NOT EXISTS public.credential_number_sequence ( woreda_id uuid NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== credential_policy @ supabase/migrations/00000000000048_task11_schema_gaps.sql:375 =====
CREATE TABLE IF NOT EXISTS public.credential_policy ( credential_policy_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, expiry_months integer, renewal_window_days integer, max_reissue_count integer, enabled_request_types text[] DEFAULT ARRAY[]::text[] NOT NULL, updated_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT credential_policy_pkey PRIMARY KEY (credential_policy_id), CONSTRAINT credential_policy_woreda_id_key UNIQUE (woreda_id) );

-- ===== credential_print_log @ supabase/migrations/00000000000000_baseline.sql:54 =====
CREATE TABLE IF NOT EXISTS public.credential_print_log ( credential_print_log_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, credential_id uuid NOT NULL, printed_by_user_id uuid, print_type text NOT NULL, print_reason text NOT NULL, is_reprint boolean DEFAULT false NOT NULL, reprint_reason text, reprint_authorized_by_user_id uuid, printer_name text, copies_count integer DEFAULT 1 NOT NULL, printed_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== credential_request @ supabase/migrations/00000000000000_baseline.sql:68 =====
CREATE TABLE IF NOT EXISTS public.credential_request ( credential_request_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, request_number text NOT NULL, resident_id uuid NOT NULL, household_id uuid, issuing_kebele_id uuid NOT NULL, request_type text NOT NULL, credential_type text DEFAULT 'card'::text NOT NULL, status text DEFAULT 'draft'::text NOT NULL, prior_credential_id uuid, duplicate_flag boolean DEFAULT false NOT NULL, duplicate_notes text, verification_checklist jsonb, return_reason text, reject_reason text, requested_by_user_id uuid, verified_by_user_id uuid, approved_by_user_id uuid, approval_decision_at timestamp with time zone, payment_id uuid, credential_id uuid, submitted_at timestamp with time zone, closed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, supporting_document_path text, supporting_document_name text, verified_at timestamp with time zone, notes text );

-- ===== credential_request_sequence @ supabase/migrations/00000000000000_baseline.sql:99 =====
CREATE TABLE IF NOT EXISTS public.credential_request_sequence ( woreda_id uuid NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== credential_request_status_history @ supabase/migrations/00000000000000_baseline.sql:104 =====
CREATE TABLE IF NOT EXISTS public.credential_request_status_history ( id uuid DEFAULT gen_random_uuid() NOT NULL, credential_request_id uuid NOT NULL, old_status text, new_status text NOT NULL, changed_by_user_id uuid, change_reason text, changed_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== credential_status_history @ supabase/migrations/00000000000000_baseline.sql:113 =====
CREATE TABLE IF NOT EXISTS public.credential_status_history ( id uuid DEFAULT gen_random_uuid() NOT NULL, credential_id uuid NOT NULL, old_status text, new_status text NOT NULL, changed_by_user_id uuid, change_reason text, changed_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== credential_verification_log @ supabase/migrations/00000000000034_task3_harden_credential_verification.sql:78 =====
CREATE TABLE public.credential_verification_log ( id uuid DEFAULT gen_random_uuid() PRIMARY KEY, woreda_id uuid REFERENCES public.woreda(woreda_id), matched_credential_id uuid REFERENCES public.residence_credential(credential_id), attempted_value_kind text NOT NULL CHECK (attempted_value_kind IN ('token', 'credential_number')), attempted_value text NOT NULL CHECK (length(attempted_value) <= 512), result text NOT NULL CHECK (result IN ('valid', 'invalid', 'not_found', 'rate_limited')), is_staff_caller boolean NOT NULL DEFAULT false, source_ip text, created_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== fee_schedule @ supabase/migrations/00000000000000_baseline.sql:122 =====
CREATE TABLE IF NOT EXISTS public.fee_schedule ( fee_schedule_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, service_type text NOT NULL, standard_fee numeric(10,2) DEFAULT 0 NOT NULL, penalty_rate numeric(10,2) DEFAULT 0 NOT NULL, status text DEFAULT 'active'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== household @ supabase/migrations/00000000000000_baseline.sql:132 =====
CREATE TABLE IF NOT EXISTS public.household ( household_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, kebele_id uuid NOT NULL, house_number text NOT NULL, house_label text, occupancy_status text DEFAULT 'occupied'::text NOT NULL, address_line text, gps_lat numeric(10,8), gps_lng numeric(11,8), active_flag boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, household_head_resident_id uuid, phone_number text, po_box text, email text, house_type text, house_type_other text, rent_amount numeric(12,2), spouse_resident_id uuid, alternate_head_resident_id uuid, sub_woreda text );

-- ===== household_change_log @ supabase/migrations/00000000000000_baseline.sql:156 =====
CREATE TABLE IF NOT EXISTS public.household_change_log ( id uuid DEFAULT gen_random_uuid() NOT NULL, household_id uuid NOT NULL, change_type text NOT NULL, change_date date DEFAULT CURRENT_DATE NOT NULL, registered_by_user_id uuid, clerk_comment text, household_head_signed boolean DEFAULT false NOT NULL, clerk_signed boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, woreda_id uuid NOT NULL, old_value_json jsonb, new_value_json jsonb );

-- ===== household_location @ supabase/migrations/00000000000048_task11_schema_gaps.sql:139 =====
CREATE TABLE IF NOT EXISTS public.household_location ( household_location_id uuid DEFAULT gen_random_uuid() NOT NULL, household_id uuid NOT NULL, woreda_id uuid NOT NULL, gps_lat numeric, gps_lng numeric, map_reference text, captured_at timestamp with time zone DEFAULT now() NOT NULL, captured_by uuid, CONSTRAINT household_location_pkey PRIMARY KEY (household_location_id), CONSTRAINT household_location_household_id_key UNIQUE (household_id) );

-- ===== id_card_template @ supabase/migrations/00000000000000_baseline.sql:170 =====
CREATE TABLE IF NOT EXISTS public.id_card_template ( template_type text NOT NULL, background_image_url text, status text DEFAULT 'draft'::text NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid );

-- ===== id_card_template_field @ supabase/migrations/00000000000000_baseline.sql:177 =====
CREATE TABLE IF NOT EXISTS public.id_card_template_field ( template_field_id uuid DEFAULT gen_random_uuid() NOT NULL, template_type text NOT NULL, field_key text NOT NULL, x numeric NOT NULL, y numeric NOT NULL, width numeric NOT NULL, height numeric NOT NULL, font_size numeric, font_weight text, text_align text DEFAULT 'left'::text NOT NULL, z_index integer DEFAULT 0 NOT NULL, canvas_width numeric DEFAULT 1688 NOT NULL, canvas_height numeric DEFAULT 1063 NOT NULL, field_type text DEFAULT 'text'::text NOT NULL, color text DEFAULT '#000000'::text NOT NULL, font_family text DEFAULT 'Inter'::text NOT NULL, font_style text DEFAULT 'normal'::text NOT NULL, text_decoration text DEFAULT 'none'::text NOT NULL, binding_mode text DEFAULT 'bound'::text NOT NULL, static_value text );

-- ===== id_card_template_field_draft @ supabase/migrations/00000000000010_id_card_template_draft.sql:30 =====
CREATE TABLE public.id_card_template_field_draft ( template_field_id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, template_type text NOT NULL, field_key text NOT NULL, x numeric NOT NULL, y numeric NOT NULL, width numeric NOT NULL, height numeric NOT NULL, font_size numeric, font_weight text, text_align text DEFAULT 'left'::text NOT NULL, z_index integer DEFAULT 0 NOT NULL, canvas_width numeric DEFAULT 1688 NOT NULL, canvas_height numeric DEFAULT 1063 NOT NULL, field_type text DEFAULT 'text'::text NOT NULL, color text DEFAULT '#000000'::text NOT NULL, font_family text DEFAULT 'Inter'::text NOT NULL, font_style text DEFAULT 'normal'::text NOT NULL, text_decoration text DEFAULT 'none'::text NOT NULL, binding_mode text DEFAULT 'bound'::text NOT NULL, static_value text, CONSTRAINT id_card_template_field_draft_template_type_check CHECK (template_type = ANY (ARRAY['card_front'::text, 'card_back'::text, 'certificate'::text])), CONSTRAINT id_card_template_field_draft_field_type_check CHECK (field_type = ANY (ARRAY['text'::text, 'image'::text])), CONSTRAINT id_card_template_field_draft_font_style_check CHECK (font_style = ANY (ARRAY['normal'::text, 'italic'::text])), CONSTRAINT id_card_template_field_draft_text_decoration_check CHECK (text_decoration = ANY (ARRAY['none'::text, 'underline'::text])), CONSTRAINT id_card_template_field_draft_binding_mode_check CHECK (binding_mode = ANY (ARRAY['bound'::text, 'static'::text])), CONSTRAINT id_card_template_field_draft_type_key_key UNIQUE (template_type, field_key) );

-- ===== kebele @ supabase/migrations/00000000000000_baseline.sql:199 =====
CREATE TABLE IF NOT EXISTS public.kebele ( kebele_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, kebele_number text NOT NULL, kebele_name_en text NOT NULL, kebele_name_am text NOT NULL, status text DEFAULT 'active'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== kebele_rental_house @ supabase/migrations/00000000000000_baseline.sql:208 =====
CREATE TABLE IF NOT EXISTS public.kebele_rental_house ( rental_house_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, kebele_id uuid NOT NULL, house_number text NOT NULL, address_line text, bedrooms integer, monthly_rent_standard numeric(10,2), occupancy_status text DEFAULT 'vacant'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== office @ supabase/migrations/00000000000048_task11_schema_gaps.sql:57 =====
CREATE TABLE IF NOT EXISTS public.office ( office_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, office_code text NOT NULL, office_name text NOT NULL, is_main boolean DEFAULT true NOT NULL, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT office_pkey PRIMARY KEY (office_id), CONSTRAINT office_woreda_id_key UNIQUE (woreda_id) );

-- ===== payment @ supabase/migrations/00000000000000_baseline.sql:220 =====
CREATE TABLE IF NOT EXISTS public.payment ( payment_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, household_id uuid, resident_id uuid, payment_type text NOT NULL, amount numeric(12,2) NOT NULL, payment_date date NOT NULL, channel text DEFAULT 'cash'::text NOT NULL, reference_no text, status text DEFAULT 'pending'::text NOT NULL, posted_by_user_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, credential_request_id uuid, rental_request_id uuid, service_request_id uuid );

-- ===== payment_reconciliation_exception @ supabase/migrations/00000000000078_rental_phase3_settlement.sql:230 =====
CREATE TABLE IF NOT EXISTS public.payment_reconciliation_exception ( exception_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid REFERENCES public.rent_account(rent_account_id), external_reference text, received_amount numeric(14, 2) NOT NULL CHECK (received_amount >= 0), received_amount_enc bytea, expected_settlement_amount numeric(14, 2) CHECK (expected_settlement_amount IS NULL OR expected_settlement_amount >= 0), expected_settlement_amount_enc bytea, exception_type text NOT NULL CHECK (exception_type IN ('amount_mismatch', 'duplicate', 'unknown_month', 'other')), status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'under_review', 'resolved', 'rejected')), resolution_note text, resolved_by uuid REFERENCES public.app_user(user_id), resolved_at timestamptz, created_by uuid REFERENCES public.app_user(user_id), created_at timestamptz NOT NULL DEFAULT now() );

-- ===== rate_limit_bucket @ supabase/migrations/00000000000022_rate_limit.sql:25 =====
CREATE TABLE public.rate_limit_bucket ( bucket_key text NOT NULL, window_start timestamptz NOT NULL, request_count integer DEFAULT 1 NOT NULL, PRIMARY KEY (bucket_key, window_start) );

-- ===== receipt @ supabase/migrations/00000000000000_baseline.sql:237 =====
CREATE TABLE IF NOT EXISTS public.receipt ( receipt_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, payment_id uuid NOT NULL, receipt_number text NOT NULL, receipt_date date NOT NULL, total_amount numeric(12,2) NOT NULL, cash_bank_channel text NOT NULL, printed_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== receipt_sequence @ supabase/migrations/00000000000000_baseline.sql:248 =====
CREATE TABLE IF NOT EXISTS public.receipt_sequence ( woreda_id uuid NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== rent_account @ supabase/migrations/00000000000076_rental_phase2_financial_core.sql:88 =====
CREATE TABLE IF NOT EXISTS public.rent_account ( rent_account_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), occupancy_id uuid NOT NULL REFERENCES public.rental_occupancy(occupancy_id), rental_house_id uuid NOT NULL REFERENCES public.kebele_rental_house(rental_house_id), kebele_id uuid NOT NULL REFERENCES public.kebele(kebele_id), resident_id uuid NOT NULL REFERENCES public.resident(resident_id), household_id uuid REFERENCES public.household(household_id), account_number text NOT NULL, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'terminated', 'closed')), billing_start_period_key text NOT NULL CHECK (billing_start_period_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'), billing_end_period_key text CHECK (billing_end_period_key IS NULL OR billing_end_period_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'), created_by uuid REFERENCES public.app_user(user_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (woreda_id, account_number) );

-- ===== rent_account_sequence @ supabase/migrations/00000000000076_rental_phase2_financial_core.sql:75 =====
CREATE TABLE IF NOT EXISTS public.rent_account_sequence ( woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), seq_year smallint NOT NULL, last_value integer NOT NULL DEFAULT 0, PRIMARY KEY (woreda_id, seq_year) );

-- ===== rent_charge @ supabase/migrations/00000000000076_rental_phase2_financial_core.sql:210 =====
CREATE TABLE IF NOT EXISTS public.rent_charge ( rent_charge_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid NOT NULL REFERENCES public.rent_account(rent_account_id), occupancy_id uuid NOT NULL REFERENCES public.rental_occupancy(occupancy_id), ethiopian_year integer NOT NULL CHECK (ethiopian_year > 0), ethiopian_month integer NOT NULL CHECK (ethiopian_month BETWEEN 1 AND 12), ethiopian_period_key text NOT NULL CHECK (ethiopian_period_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'), charge_date date NOT NULL DEFAULT current_date, due_date date NOT NULL, base_rent_amount numeric(14, 2) NOT NULL CHECK (base_rent_amount > 0), base_rent_amount_enc bytea, approved_adjustment_amount numeric(14, 2) NOT NULL DEFAULT 0, approved_adjustment_amount_enc bytea, total_amount numeric(14, 2) NOT NULL CHECK (total_amount > 0), total_amount_enc bytea, status text NOT NULL DEFAULT 'due' CHECK (status IN ('scheduled', 'due', 'overdue', 'paid', 'waived', 'cancelled')), settled_at timestamptz, settled_by_payment_id uuid REFERENCES public.payment(payment_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (rent_account_id, ethiopian_period_key), CHECK (total_amount = base_rent_amount + approved_adjustment_amount) );

-- ===== rent_payment_settlement @ supabase/migrations/00000000000078_rental_phase3_settlement.sql:168 =====
CREATE TABLE IF NOT EXISTS public.rent_payment_settlement ( settlement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), payment_id uuid NOT NULL REFERENCES public.rental_payment(payment_id), rent_charge_id uuid NOT NULL REFERENCES public.rent_charge(rent_charge_id), settlement_amount numeric(14, 2) NOT NULL CHECK (settlement_amount > 0), settlement_amount_enc bytea, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'reversed')), settled_at timestamptz NOT NULL DEFAULT now(), created_by uuid REFERENCES public.app_user(user_id), UNIQUE (payment_id, rent_charge_id) );

-- ===== rent_rate_history @ supabase/migrations/00000000000076_rental_phase2_financial_core.sql:171 =====
CREATE TABLE IF NOT EXISTS public.rent_rate_history ( rent_rate_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid NOT NULL REFERENCES public.rent_account(rent_account_id), effective_period_key text NOT NULL CHECK (effective_period_key ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'), monthly_amount numeric(14, 2) NOT NULL CHECK (monthly_amount > 0), monthly_amount_enc bytea, change_reason text, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'superseded')), approved_by uuid REFERENCES public.app_user(user_id), approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (rent_account_id, effective_period_key) );

-- ===== rent_reminder @ supabase/migrations/00000000000080_rental_phase4_arrears.sql:946 =====
CREATE TABLE IF NOT EXISTS public.rent_reminder ( reminder_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid NOT NULL REFERENCES public.rent_account(rent_account_id), reminder_type text NOT NULL CHECK (reminder_type IN ('rent_due', 'rent_overdue', 'plan_due', 'plan_overdue', 'escalation')), snapshot_month_count integer, snapshot_amount numeric(14, 2), snapshot_amount_enc bytea, snapshot_oldest_overdue_period text, delivery_channel text NOT NULL DEFAULT 'erp' CHECK (delivery_channel IN ('erp', 'sms', 'print')), delivery_status text NOT NULL DEFAULT 'pending' CHECK (delivery_status IN ('pending', 'sent', 'failed')), created_at timestamptz NOT NULL DEFAULT now() );

-- ===== rental_occupancy @ supabase/migrations/00000000000000_baseline.sql:253 =====
CREATE TABLE IF NOT EXISTS public.rental_occupancy ( occupancy_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, rental_house_id uuid NOT NULL, resident_id uuid NOT NULL, household_id uuid, rent_start_date date NOT NULL, rent_amount numeric(10,2) NOT NULL, status text DEFAULT 'active'::text NOT NULL, termination_date date, termination_reason text, originating_request_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== rental_occupancy_request @ supabase/migrations/00000000000000_baseline.sql:268 =====
CREATE TABLE IF NOT EXISTS public.rental_occupancy_request ( rental_request_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, request_number text NOT NULL, rental_house_id uuid NOT NULL, resident_id uuid NOT NULL, household_id uuid, request_type text NOT NULL, rent_start_date date, rent_amount numeric(10,2), termination_date date, termination_reason text, existing_occupancy_id uuid, status text DEFAULT 'draft'::text NOT NULL, verification_checklist jsonb, return_reason text, reject_reason text, requested_by_user_id uuid, verified_by_user_id uuid, verified_at timestamp with time zone, approved_by_user_id uuid, approval_decision_at timestamp with time zone, resulting_occupancy_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== rental_payment @ supabase/migrations/00000000000078_rental_phase3_settlement.sql:136 =====
CREATE TABLE IF NOT EXISTS public.rental_payment ( payment_id uuid PRIMARY KEY REFERENCES public.payment(payment_id), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), rent_account_id uuid NOT NULL REFERENCES public.rent_account(rent_account_id), payer_resident_id uuid REFERENCES public.resident(resident_id), reference_number text, idempotency_key text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (woreda_id, idempotency_key) );

-- ===== rental_policy @ supabase/migrations/00000000000071_rental_phase0_policy.sql:138 =====
CREATE TABLE IF NOT EXISTS public.rental_policy ( rental_policy_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL UNIQUE REFERENCES public.woreda(woreda_id), due_rule text NOT NULL DEFAULT 'fixed_day_after_period_start' CHECK (due_rule = 'fixed_day_after_period_start'), due_day integer NOT NULL DEFAULT 10 CHECK (due_day BETWEEN 1 AND 30), reminder_days_before_due integer NOT NULL DEFAULT 5 CHECK (reminder_days_before_due >= 0), reminder_days_after_overdue integer NOT NULL DEFAULT 3 CHECK (reminder_days_after_overdue >= 0), escalation_after_overdue_months integer NOT NULL DEFAULT 3 CHECK (escalation_after_overdue_months >= 1), reminder_channels text[] NOT NULL DEFAULT ARRAY['erp', 'print']::text[] CHECK (reminder_channels <@ ARRAY['erp', 'sms', 'print']::text[]), plan_max_installments integer NOT NULL DEFAULT 12 CHECK (plan_max_installments BETWEEN 1 AND 36), block_on_rental_arrears boolean NOT NULL DEFAULT false, plan_compliance_effect text NOT NULL DEFAULT 'reduce_severity' CHECK (plan_compliance_effect IN ('reduce_severity', 'no_effect')), emergency_exemption boolean NOT NULL DEFAULT true, termination_final_period_rule text NOT NULL DEFAULT 'through_termination_month' CHECK (termination_final_period_rule = 'through_termination_month'), rate_change_requires_approval boolean NOT NULL DEFAULT true, waiver_requires_role text NOT NULL DEFAULT 'supervisor' CHECK (waiver_requires_role IN ('supervisor', 'tenant_admin')), waiver_max_amount numeric(14, 2) CHECK (waiver_max_amount IS NULL OR waiver_max_amount >= 0), billing_invocation_mode text NOT NULL DEFAULT 'manual' CHECK (billing_invocation_mode IN ('manual', 'scheduled')), updated_by uuid REFERENCES public.app_user(user_id), updated_at timestamptz NOT NULL DEFAULT now(), created_at timestamptz NOT NULL DEFAULT now() );

-- ===== rental_request_document @ supabase/migrations/00000000000000_baseline.sql:294 =====
CREATE TABLE IF NOT EXISTS public.rental_request_document ( document_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, rental_request_id uuid NOT NULL, document_type text NOT NULL, file_name text NOT NULL, storage_path text NOT NULL, file_size_bytes integer, content_type text, uploaded_by_user_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== rental_request_sequence @ supabase/migrations/00000000000000_baseline.sql:307 =====
CREATE TABLE IF NOT EXISTS public.rental_request_sequence ( woreda_id uuid NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== residence_credential @ supabase/migrations/00000000000000_baseline.sql:312 =====
CREATE TABLE IF NOT EXISTS public.residence_credential ( credential_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, resident_id uuid NOT NULL, issuing_kebele_id uuid NOT NULL, credential_number text NOT NULL, serial_number text NOT NULL, credential_type text DEFAULT 'card'::text NOT NULL, status text DEFAULT 'ready_to_print'::text NOT NULL, issue_date date, expiry_date date, reason_for_issue text, reissue_count integer DEFAULT 0 NOT NULL, qr_payload text, printed_at timestamp with time zone, revoked_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, requested_by_user_id uuid, rejection_reason text, credential_request_id uuid, activated_at timestamp with time zone, replaced_at timestamp with time zone, issued_recipient_name text, revoked_reason text, revoked_by_user_id uuid );

-- ===== resident @ supabase/migrations/00000000000000_baseline.sql:339 =====
CREATE TABLE IF NOT EXISTS public.resident ( resident_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, resident_number text NOT NULL, full_name text NOT NULL, full_name_am text, sex text NOT NULL, date_of_birth date NOT NULL, marital_status text NOT NULL, current_household_id uuid, relation_to_head text, phone_number text, national_id_no text, residency_status text DEFAULT 'active'::text NOT NULL, photo_url text, active_flag boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, father_name text, grandfather_name text, mother_full_name text, ethnicity text, religion text, residency_start_date date, current_residence_extra jsonb, birth_place jsonb, work_info jsonb, former_residence jsonb, first_name text, email text );

-- ===== resident_document @ supabase/migrations/00000000000004_resident_documents.sql:19 =====
CREATE TABLE IF NOT EXISTS public.resident_document ( document_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, resident_id uuid NOT NULL, household_id uuid, document_label text NOT NULL, file_name text NOT NULL, storage_path text NOT NULL, file_size_bytes integer, content_type text DEFAULT 'application/pdf'::text NOT NULL, uploaded_by_user_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT resident_document_pkey PRIMARY KEY (document_id), CONSTRAINT resident_document_content_type_check CHECK ((content_type = 'application/pdf'::text)) );

-- ===== resident_number_sequence @ supabase/migrations/00000000000000_baseline.sql:370 =====
CREATE TABLE IF NOT EXISTS public.resident_number_sequence ( woreda_id uuid NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== role_permission @ supabase/migrations/00000000000000_baseline.sql:374 =====
CREATE TABLE IF NOT EXISTS public.role_permission ( woreda_id uuid NOT NULL, role_name text NOT NULL, permission_key text NOT NULL, is_granted boolean DEFAULT false NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== service_request @ supabase/migrations/00000000000000_baseline.sql:382 =====
CREATE TABLE IF NOT EXISTS public.service_request ( service_request_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, request_number text NOT NULL, service_type_id uuid NOT NULL, category text DEFAULT 'letter'::text NOT NULL, resident_id uuid, household_id uuid, kebele_id uuid, applicant_name text, applicant_phone text, status text DEFAULT 'submitted'::text NOT NULL, priority text DEFAULT 'normal'::text NOT NULL, purpose text, addressed_to text, details text, subject text, respondent_name text, incident_date date, incident_place text, fee_amount numeric DEFAULT 0 NOT NULL, verification_checklist jsonb, return_reason text, reject_reason text, resolution_notes text, requested_by_user_id uuid, verified_by_user_id uuid, verified_at timestamp with time zone, approved_by_user_id uuid, approval_decision_at timestamp with time zone, issued_by_user_id uuid, issued_at timestamp with time zone, closed_at timestamp with time zone, payment_id uuid, submitted_at timestamp with time zone DEFAULT now() NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, verification_token text, issued_letter_html text, letter_summary text );

-- ===== service_request_attachment @ supabase/migrations/00000000000000_baseline.sql:423 =====
CREATE TABLE IF NOT EXISTS public.service_request_attachment ( attachment_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, service_request_id uuid NOT NULL, document_type text NOT NULL, file_name text NOT NULL, storage_path text NOT NULL, file_size_bytes integer, content_type text, uploaded_by_user_id uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== service_request_checkpoint @ supabase/migrations/00000000000083_rental_phase5_checkpoint.sql:142 =====
CREATE TABLE IF NOT EXISTS public.service_request_checkpoint ( checkpoint_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), service_request_id uuid NOT NULL UNIQUE REFERENCES public.service_request(service_request_id), resident_id uuid REFERENCES public.resident(resident_id), rental_house_id uuid REFERENCES public.kebele_rental_house(rental_house_id), rent_account_id uuid REFERENCES public.rent_account(rent_account_id), has_active_occupancy boolean NOT NULL DEFAULT false, overdue_month_count integer NOT NULL DEFAULT 0, overdue_total numeric(14, 2) NOT NULL DEFAULT 0, overdue_total_enc bytea, oldest_overdue_period text, has_active_plan boolean NOT NULL DEFAULT false, active_plan_id uuid REFERENCES public.arrears_repayment_plan(plan_id), would_block boolean NOT NULL DEFAULT false, override_used boolean NOT NULL DEFAULT false, override_reason text, resolved_at timestamptz NOT NULL DEFAULT now() );

-- ===== service_request_sequence @ supabase/migrations/00000000000000_baseline.sql:436 =====
CREATE TABLE IF NOT EXISTS public.service_request_sequence ( woreda_id uuid NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== service_request_status_history @ supabase/migrations/00000000000000_baseline.sql:441 =====
CREATE TABLE IF NOT EXISTS public.service_request_status_history ( id uuid DEFAULT gen_random_uuid() NOT NULL, service_request_id uuid NOT NULL, old_status text, new_status text NOT NULL, changed_by_user_id uuid, change_reason text, changed_at timestamp with time zone DEFAULT now() NOT NULL );

-- ===== service_type @ supabase/migrations/00000000000000_baseline.sql:450 =====
CREATE TABLE IF NOT EXISTS public.service_type ( service_type_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, code text NOT NULL, name_am text NOT NULL, name_en text NOT NULL, category text DEFAULT 'letter'::text NOT NULL, fee_amount numeric DEFAULT 0 NOT NULL, requires_payment boolean DEFAULT false NOT NULL, requires_approval boolean DEFAULT true NOT NULL, required_documents jsonb DEFAULT '[]'::jsonb NOT NULL, letter_body_template text, sort_order integer DEFAULT 0 NOT NULL, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, letter_body_html text );

-- ===== tenant_module_config @ supabase/migrations/00000000000000_baseline.sql:468 =====
CREATE TABLE IF NOT EXISTS public.tenant_module_config ( woreda_id uuid NOT NULL, module_key text NOT NULL, is_enabled boolean DEFAULT true NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid );

-- ===== tenant_role @ supabase/migrations/00000000000038_task13_tenant_role_schema.sql:24 =====
CREATE TABLE public.tenant_role ( tenant_role_id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id), name text NOT NULL, description text, is_active boolean DEFAULT true NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, created_by uuid REFERENCES public.app_user(user_id), updated_by uuid REFERENCES public.app_user(user_id), UNIQUE (woreda_id, name) );

-- ===== tenant_role_permission @ supabase/migrations/00000000000038_task13_tenant_role_schema.sql:47 =====
CREATE TABLE public.tenant_role_permission ( tenant_role_id uuid NOT NULL REFERENCES public.tenant_role(tenant_role_id) ON DELETE CASCADE, permission_key text NOT NULL, is_granted boolean DEFAULT false NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid REFERENCES public.app_user(user_id), PRIMARY KEY (tenant_role_id, permission_key), CONSTRAINT tenant_role_permission_no_reserved_keys CHECK (permission_key <> ALL (ARRAY[ 'credential.approve', 'civil.approve', 'tenant.manage', 'platform.manage', 'tenant.create', 'credential.configure_policy', 'user.manage', 'credential.revoke' ])) );

-- ===== user_permission_override @ supabase/migrations/00000000000017_user_permission_overrides.sql:26 =====
CREATE TABLE public.user_permission_override ( user_id uuid NOT NULL REFERENCES public.app_user(user_id) ON DELETE CASCADE, woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id) ON DELETE CASCADE, permission_key text NOT NULL, is_granted boolean NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), updated_by uuid REFERENCES public.app_user(user_id) ON DELETE SET NULL, PRIMARY KEY (user_id, permission_key), CONSTRAINT user_permission_override_no_locked_keys CHECK (permission_key <> ALL (ARRAY['credential.approve', 'civil.approve', 'tenant.manage'])) );

-- ===== vital_event @ supabase/migrations/00000000000000_baseline.sql:475 =====
CREATE TABLE IF NOT EXISTS public.vital_event ( vital_event_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_id uuid NOT NULL, resident_id uuid, household_id uuid, event_type text NOT NULL, event_number text NOT NULL, event_date date NOT NULL, registration_date date, status text DEFAULT 'pending'::text NOT NULL, notes text, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, event_details jsonb, requested_by_user_id uuid, verified_by_user_id uuid, verified_at timestamp with time zone, approved_by_user_id uuid, approval_decision_at timestamp with time zone, return_reason text, reject_reason text, verification_checklist jsonb, source_document_no text, issued_at timestamp with time zone, issued_by_user_id uuid );

-- ===== vital_event_sequence @ supabase/migrations/00000000000000_baseline.sql:501 =====
CREATE TABLE IF NOT EXISTS public.vital_event_sequence ( woreda_id uuid NOT NULL, event_type text NOT NULL, seq_year smallint NOT NULL, last_value integer DEFAULT 0 NOT NULL );

-- ===== woreda @ supabase/migrations/00000000000000_baseline.sql:507 =====
CREATE TABLE IF NOT EXISTS public.woreda ( woreda_id uuid DEFAULT gen_random_uuid() NOT NULL, woreda_code text NOT NULL, woreda_name_en text NOT NULL, woreda_name_am text NOT NULL, status text DEFAULT 'active'::text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, woreda_numeric_code smallint NOT NULL );

-- ===== woreda_settings @ supabase/migrations/00000000000000_baseline.sql:517 =====
CREATE TABLE IF NOT EXISTS public.woreda_settings ( woreda_id uuid NOT NULL, credential_issuance_fee numeric(10,2) DEFAULT 0 NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, updated_by uuid, logo_url text, stamp_url text, supervisor_signature_url text, woreda_name_display text, resident_number_format text DEFAULT '{WOREDA_CODE}-{SEQ:6}'::text NOT NULL, address_line text, contact_phone text, contact_email text );

-- ===== workflow_status_history @ supabase/migrations/00000000000058_task14a_civil_registration_fsm.sql:37 =====
CREATE TABLE IF NOT EXISTS public.workflow_status_history ( id uuid PRIMARY KEY DEFAULT gen_random_uuid(), woreda_id uuid NOT NULL REFERENCES public.woreda(woreda_id) ON DELETE CASCADE, entity text NOT NULL, entity_id uuid NOT NULL, old_status text, new_status text NOT NULL, changed_at timestamptz NOT NULL DEFAULT now(), changed_by_user_id uuid REFERENCES public.app_user(user_id), change_reason text );

-- ===== workflow_transition @ supabase/migrations/00000000000025_workflow_engine.sql:60 =====
CREATE TABLE IF NOT EXISTS public.workflow_transition ( workflow_transition_id uuid DEFAULT gen_random_uuid() NOT NULL, entity text NOT NULL, from_status text NOT NULL, to_status text NOT NULL, required_permission text, is_system boolean DEFAULT false NOT NULL, note text, created_at timestamp with time zone DEFAULT now() NOT NULL );

