"""Build 03-insa-compliance-matrix.md from every agent's checklist[] entries.

Rule for an ID assessed by several agents (usually each owning one part of it):
  1. audit-verifier's verdict wins when present (it re-checked against the other agents' evidence).
  2. Otherwise the worst assessed status wins: FAIL < PARTIAL < PASS. UNVERIFIED parts are ignored
     unless every part is UNVERIFIED. N/A only when every part is N/A.
Scoring: PASS=1, PARTIAL=0.5, FAIL=0; N/A excluded; UNVERIFIED excluded and counted separately.
"""
import json, glob, os, re, collections

os.chdir(os.path.dirname(os.path.abspath(__file__)) + "/..")
ref = open("reference/INSA-CHECKLIST.md").read()

# Checklist IDs and requirement text, in order, from the verbatim appendix.
items = []
for line in ref.splitlines():
    m = re.match(r"^\| ([A-Z]{1,4}-\d{2}) \| ([^|]+)\|", line)
    if m:
        items.append((m.group(1), m.group(2).strip()))

def norm(i):
    i = i.replace("INSA ", "").strip()
    m = re.match(r"^([A-Z]{1,4})-?(\d{1,2})", i)
    return f"{m.group(1)}-{int(m.group(2)):02d}" if m else i

entries = collections.defaultdict(list)
for f in sorted(glob.glob("findings/*.json")):
    j = json.load(open(f))
    agent = j.get("agent") or os.path.basename(f)[:-5]
    for c in j.get("checklist", []):
        entries[norm(c["id"])].append((agent.replace("audit-", ""), c.get("status", "UNVERIFIED").split()[0].upper(),
                                        (c.get("note") or "").replace("\n", " "), c.get("evidence") or ""))

rank = {"FAIL": 0, "PARTIAL": 1, "PASS": 2}
def decide(es):
    # Live verification (2026-09-25) is newer primary evidence than any static verdict.
    for a, s, n, e in es:
        if a == "live-verification":
            return s, a
    for a, s, n, e in es:
        if a == "verifier":
            return s, a
    assessed = [x for x in es if x[1] in rank]
    if assessed:
        w = min(assessed, key=lambda x: rank[x[1]])
        return w[1], w[0]
    if es and all(x[1] == "N/A" for x in es):
        return "N/A", es[0][0]
    return "UNVERIFIED", es[0][0] if es else "—"

def phase(i):
    p = i.split("-")[0]
    return {"A": "A. Architecture & Design", "B": "B. Stack & Inventory", "C": "C. Coding & Implementation",
            "D": "D. Security Functionality Doc", "E": "E. API Security", "F": "F. Testing Scope",
            "G": "G. Living Documentation", "ET": "Appendix B — Ethiopian Locale"}.get(p, "H. Project-specific extensions")

pts = {"PASS": 1, "PARTIAL": 0.5, "FAIL": 0}
score = collections.defaultdict(lambda: [0.0, 0, 0, 0])  # points, scored, unverified, na
rows = []
for i, req in items:
    es = entries.get(i, [])
    st, owner = decide(es)
    ph = phase(i)
    if st in pts:
        score[ph][0] += pts[st]; score[ph][1] += 1
    elif st == "UNVERIFIED":
        score[ph][2] += 1
    else:
        score[ph][3] += 1
    note = " · ".join(f"**{a}** {s}: {n[:220]}" for a, s, n, e in es) or "No agent assessed this item."
    rows.append((ph, i, req, st, owner, note))

def pct(p, n):
    return f"{100 * p / n:.1f}%" if n else "—"

L = ["# 03 — INSA Compliance Matrix", "",
     "Every Appendix A control (INSA Technical Development Checklist, implemented as testable controls) and every "
     "Appendix B Ethiopian-locale control, with the final status, the owning agent and each agent's evidence note. "
     "Full evidence is in `findings/<agent>.md`. Generated by `raw/build-matrix.py`.", "",
     "Scoring: PASS = 1, PARTIAL = 0.5, FAIL = 0; N/A excluded; UNVERIFIED excluded from the percentage and counted separately. "
     "Where several agents assessed parts of one control, the verifier's verdict wins, otherwise the worst assessed part.", "",
     "## Score", "", "| Phase | Score | Scored items | UNVERIFIED | N/A |", "|---|---|---|---|---|"]
core = [0.0, 0, 0, 0]; allp = [0.0, 0, 0, 0]
for ph in sorted(score):
    p, n, u, na = score[ph]
    L.append(f"| {ph} | {pct(p, n)} ({p:g}/{n}) | {n} | {u} | {na} |")
    for acc in ([core] if not ph.startswith("Appendix B") else []) + [allp]:
        acc[0] += p; acc[1] += n; acc[2] += u; acc[3] += na
L.append(f"| **INSA overall (Appendix A: A–H)** | **{pct(core[0], core[1])}** ({core[0]:g}/{core[1]}) | {core[1]} | {core[2]} | {core[3]} |")
L.append(f"| **Combined incl. Appendix B** | **{pct(allp[0], allp[1])}** ({allp[0]:g}/{allp[1]}) | {allp[1]} | {allp[2]} | {allp[3]} |")
L.append("")
cnt = collections.Counter(r[3] for r in rows)
L.append("Status totals: " + ", ".join(f"{k} {cnt.get(k, 0)}" for k in ["PASS", "PARTIAL", "FAIL", "N/A", "UNVERIFIED"]) + f" (of {len(rows)} controls).")
L.append("")
cur = None
for ph, i, req, st, owner, note in rows:
    if ph != cur:
        L += ["", f"## {ph}", "", "| ID | Requirement | Status | Owner | Evidence notes (per agent) |", "|---|---|---|---|---|"]
        cur = ph
    L.append(f"| {i} | {req.replace('|', '/')} | **{st}** | {owner} | {note.replace('|', '/')} |")
open("03-insa-compliance-matrix.md", "w").write("\n".join(L) + "\n")
json.dump({ph: {"points": v[0], "scored": v[1], "unverified": v[2], "na": v[3]} for ph, v in score.items()} |
          {"_overall_appendix_a": {"points": core[0], "scored": core[1], "unverified": core[2], "pct": pct(core[0], core[1])},
           "_combined": {"points": allp[0], "scored": allp[1], "unverified": allp[2], "pct": pct(allp[0], allp[1])},
           "_status_totals": dict(cnt),
           "_items": {r[1]: r[3] for r in rows}},
          open("raw/insa-score.json", "w"), indent=2)
print(pct(core[0], core[1]), core, pct(allp[0], allp[1]), dict(cnt))
missing = [r[1] for r in rows if r[5] == "No agent assessed this item."]
print("unassessed:", missing)
