import { describe, expect, it } from "vitest";
import { CP, P, ROLE_PERMISSIONS, type Role } from "../../src/config/permissions";
import { buildPermissionsMarkdown } from "../generate-permissions-doc";

describe("generate-permissions-doc", () => {
  it("is deterministic — regenerating without a source change produces identical output", () => {
    expect(buildPermissionsMarkdown()).toBe(buildPermissionsMarkdown());
  });

  it("carries the auto-generated banner so nobody hand-edits the output", () => {
    const md = buildPermissionsMarkdown();
    expect(md).toContain("AUTO-GENERATED by scripts/generate-permissions-doc.ts");
  });

  it("lists every role as a column header, in ROLE_PERMISSIONS' own order", () => {
    const md = buildPermissionsMarkdown();
    const roles = Object.keys(ROLE_PERMISSIONS) as Role[];
    const headerLine = md.split("\n").find((l) => l.startsWith("| Permission |"));
    expect(headerLine).toBeDefined();
    for (const role of roles) {
      expect(headerLine).toContain(role);
    }
  });

  it("includes every permission key from P at least once", () => {
    const md = buildPermissionsMarkdown();
    for (const perm of Object.values(P)) {
      expect(md).toContain(`\`${perm}\``);
    }
  });

  it("includes every console permission key from CP, each with a non-empty description cell", () => {
    const md = buildPermissionsMarkdown();
    const cpRows = md.split("\n").filter((l) => l.startsWith("| `console."));
    expect(cpRows).toHaveLength(Object.values(CP).length);
    for (const key of Object.values(CP)) {
      const row = cpRows.find((l) => l.startsWith(`| \`${key}\` |`));
      expect(row, `no row for ${key}`).toBeDefined();
      const description = row!.split("|")[2]?.trim();
      expect(description, `empty description for ${key}`).toBeTruthy();
    }
  });

  it("marks a role's granted permission with a checkmark in its own column", () => {
    const md = buildPermissionsMarkdown();
    const lines = md.split("\n");
    const header = lines.find((l) => l.startsWith("| Permission |"))!;
    const roles = header
      .split("|")
      .map((c) => c.trim())
      .filter(Boolean)
      .slice(1); // drop "Permission"
    const financeIdx = roles.indexOf("finance_clerk");
    const row = lines.find((l) => l.includes("`payment.collect`"))!;
    const cells = row
      .split("|")
      .map((c) => c.trim())
      .filter((_, i) => i > 0); // drop leading empty split before first "|"
    // cells[0] is the permission cell; role columns start at index 1.
    expect(cells[financeIdx + 1]).toBe("✓");
  });
});
