#!/usr/bin/env bun
/**
 * Generates docs/permissions-matrix.md from the compiled permission source in
 * src/config/permissions.ts, so the *documentation* of who can do what can
 * never drift the way README.md's old, hand-copied RBAC section did -- it
 * listed roughly half of ROLE_PERMISSIONS' current entries and none of the
 * console-permission dimension (see the INSA remediation plan's Phase A,
 * item 2.3).
 *
 * This is a GENERATOR, not a drift check like check-role-perms-drift.ts --
 * there is no second hand-maintained copy to compare here, only one source
 * of truth (permissions.ts) and one derived artifact (this doc). Two modes:
 *
 *   bun run scripts/generate-permissions-doc.ts          (defaults to --write)
 *   bun run scripts/generate-permissions-doc.ts --write  (regenerate the doc)
 *   bun run scripts/generate-permissions-doc.ts --check  (CI: fail if the
 *     committed doc doesn't match what permissions.ts would generate)
 *
 * console_role / console_role_permission (00000000000009_console_roles.sql)
 * are NOT compiled into permissions.ts the way ROLE_PERMISSIONS is -- they're
 * ordinary per-installation table rows, admin-editable at /admin/console-roles.
 * There is nothing to generate for them beyond the fixed CP.* key list and a
 * note explaining that dynamic-data caveat; do not add a
 * "CONSOLE_ROLE_PERMISSIONS" constant to permissions.ts just to make this
 * script more symmetrical -- that would misrepresent how the feature works.
 *
 * Run: bun run generate:permissions-doc
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import * as prettier from "prettier";
import {
  ADMIN_NAV,
  CP,
  NAV_PERMISSION_MAP,
  P,
  ROLE_PERMISSIONS,
  type ConsolePermission,
  type Role,
} from "../src/config/permissions";

const OUTPUT_PATH = join(import.meta.dirname, "..", "docs", "permissions-matrix.md");

const ROLES = Object.keys(ROLE_PERMISSIONS) as Role[];

/** "resident.create" -> "resident". Groups the flat P.* list back into
 * domains without a second hand-maintained category list to keep in sync
 * with permissions.ts. */
function groupKey(permission: string): string {
  return permission.split(".")[0];
}

const GROUP_LABELS: Record<string, string> = {
  resident: "Residents",
  household: "Households",
  credential: "Credentials",
  civil: "Civil Registration",
  payment: "Payments",
  receipt: "Receipts",
  report: "Reports",
  audit: "Audit",
  tenant: "Tenant Admin",
  user: "User Management",
  platform: "Platform (Super Admin)",
  rental: "Rental Houses",
  revenue: "Revenue",
  service: "Service Requests",
  complaint: "Complaints",
  approval: "Approval Queue",
};

const CP_DESCRIPTIONS: Record<ConsolePermission, string> = {
  [CP.TENANTS_MANAGE]: "Create, edit, suspend woreda tenants",
  [CP.USERS_MANAGE]: "Manage tenant_admin accounts across all woredas",
  [CP.AUDIT_VIEW]: "View the platform-wide audit log",
  [CP.CREDENTIAL_TEMPLATE_MANAGE]: "Edit the shared ID card template (all tenants)",
  [CP.CONSOLE_USERS_MANAGE]: "Manage console_role assignments and mint new super_admin accounts",
};

function checkMark(granted: boolean): string {
  return granted ? "✓" : "";
}

export function buildPermissionsMarkdown(): string {
  const allPermissions = Object.values(P);
  const groups = new Map<string, typeof allPermissions>();
  for (const perm of allPermissions) {
    const g = groupKey(perm);
    const bucket = groups.get(g);
    if (bucket) bucket.push(perm);
    else groups.set(g, [perm]);
  }

  const lines: string[] = [];
  lines.push("<!-- AUTO-GENERATED by scripts/generate-permissions-doc.ts. Do not hand-edit --");
  lines.push(
    "     run `bun run generate:permissions-doc` after changing src/config/permissions.ts. -->",
  );
  lines.push("");
  lines.push("# Permission matrix");
  lines.push("");
  lines.push(
    "INSA Enforcer Phase 2.3 / Phase 4 Access Control. Generated from " +
      "`src/config/permissions.ts` (`ROLE_PERMISSIONS`, `CP`, `NAV_PERMISSION_MAP`, " +
      "`ADMIN_NAV`) — this is the compiled *default* matrix. Two further layers can " +
      "diverge from it per tenant/user; see the note at the bottom.",
  );
  lines.push("");

  lines.push("## Tenant permissions, by role");
  lines.push("");
  lines.push("`✓` = granted by default. Eight roles, in the order defined in `permissions.ts`.");
  lines.push("");

  for (const [group, perms] of groups) {
    const label = GROUP_LABELS[group] ?? group;
    lines.push(`### ${label}`);
    lines.push("");
    lines.push(`| Permission | ${ROLES.join(" | ")} |`);
    lines.push(`| --- | ${ROLES.map(() => "---").join(" | ")} |`);
    for (const perm of perms) {
      const row = ROLES.map((role) => checkMark(ROLE_PERMISSIONS[role].includes(perm)));
      lines.push(`| \`${perm}\` | ${row.join(" | ")} |`);
    }
    lines.push("");
  }

  lines.push("## Console permissions (`/admin`, super_admin only)");
  lines.push("");
  lines.push(
    "A second, independent permission dimension scoped to the Super Admin " +
      "Console itself (`console_role` / `console_role_permission`, " +
      "`00000000000009_console_roles.sql`). **This table is not compiled data " +
      "like the roles above** — `console_role` rows are ordinary, admin-editable " +
      "database rows (`/admin/console-roles`), not something this generator can " +
      "read from source. `app_user.console_role_id IS NULL` means **unrestricted** " +
      "— the default for every super_admin until an installation opts into scoping " +
      "one down.",
  );
  lines.push("");
  lines.push("| Key | Description |");
  lines.push("| --- | --- |");
  for (const key of Object.values(CP)) {
    lines.push(`| \`${key}\` | ${CP_DESCRIPTIONS[key]} |`);
  }
  lines.push("");

  lines.push("## Woreda portal navigation");
  lines.push("");
  lines.push(
    "`NAV_PERMISSION_MAP` — a sidebar item renders only if the signed-in user " +
      "holds its permission (`null` = always visible).",
  );
  lines.push("");
  lines.push("| Label (Amharic / English) | Route | Required permission |");
  lines.push("| --- | --- | --- |");
  for (const item of NAV_PERMISSION_MAP) {
    lines.push(
      `| ${item.labelAm} / ${item.labelEn} | \`${item.href}\` | ` +
        `${item.permission ? `\`${item.permission}\`` : "_(always visible)_"} |`,
    );
  }
  lines.push("");

  lines.push("## Admin console navigation");
  lines.push("");
  lines.push(
    "`ADMIN_NAV` — gated by console permission instead (an array means any one satisfies it).",
  );
  lines.push("");
  lines.push("| Label | Route | Required console permission |");
  lines.push("| --- | --- | --- |");
  for (const item of ADMIN_NAV) {
    const perm = item.consolePermission;
    const permText =
      perm === null
        ? "_(always visible)_"
        : Array.isArray(perm)
          ? perm.map((p) => `\`${p}\``).join(" or ")
          : `\`${perm}\``;
    lines.push(`| ${item.label} | \`${item.href}\` | ${permText} |`);
  }
  lines.push("");

  lines.push("## The full resolution chain — this doc is one layer of three");
  lines.push("");
  lines.push(
    "The matrix above is the **compiled default** only. Two more layers can " +
      "override it, resolved server-side by `current_permissions()`/`user_has_perm()` " +
      "in this exact order: a per-tenant `role_permission` override, then (winning in " +
      "both directions over that) a per-*user* `user_permission_override`. Neither is " +
      "generated here because both are live tenant data, not compiled source — see " +
      "`docs/rbac-security-forensic-review.md` for the full chain and " +
      "[`docs/erd.md`](./erd.md#tenancy--rbac) for the tables involved.",
  );
  lines.push("");

  return lines.join("\n");
}

/** Runs the raw markdown through this repo's own Prettier config, resolved
 * for OUTPUT_PATH -- `bun run format` reformats every tracked file including
 * this one (docs/*.md carries no .prettierignore exception, unlike the
 * generated files that do), so a --check comparing raw output against a
 * post-format disk file would fail on table-column padding alone, forever.
 * Formatting here instead of ignore-listing the output keeps this generator
 * consistent with the repo's stated preference (see .prettierignore's own
 * comment on why types.ts etc. are excluded: "the generator's output is not
 * prettier-shaped" -- this one's is, deliberately). */
async function formatMarkdown(raw: string): Promise<string> {
  const config = await prettier.resolveConfig(OUTPUT_PATH);
  return prettier.format(raw, { ...config, filepath: OUTPUT_PATH });
}

async function main() {
  const mode = process.argv.includes("--check") ? "check" : "write";
  const generated = await formatMarkdown(buildPermissionsMarkdown());

  if (mode === "check") {
    if (!existsSync(OUTPUT_PATH)) {
      console.error(`${OUTPUT_PATH} does not exist. Run: bun run generate:permissions-doc`);
      process.exit(1);
    }
    const onDisk = readFileSync(OUTPUT_PATH, "utf-8");
    if (onDisk !== generated) {
      console.error(
        "docs/permissions-matrix.md is stale relative to src/config/permissions.ts. " +
          "Run: bun run generate:permissions-doc",
      );
      process.exit(1);
    }
    console.log("OK: docs/permissions-matrix.md matches src/config/permissions.ts.");
    return;
  }

  writeFileSync(OUTPUT_PATH, generated);
  console.log(`Wrote ${OUTPUT_PATH}`);
}

// Only run as a CLI -- importing this module (e.g. from a unit test) must not
// call process.exit() as a side effect of module load.
if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
