/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as WoredaRouteImport } from './routes/woreda'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminConsoleRolesRouteImport } from './routes/admin.console-roles'
import { Route as AdminCredentialTemplateRouteImport } from './routes/admin.credential-template'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as VTokenRouteImport } from './routes/v.$token'
import { Route as WoredaApprovalsRouteImport } from './routes/woreda.approvals'
import { Route as WoredaAuditRouteImport } from './routes/woreda.audit'
import { Route as WoredaCivilRouteImport } from './routes/woreda.civil'
import { Route as WoredaComplaintsRouteImport } from './routes/woreda.complaints'
import { Route as WoredaCredentialsRouteImport } from './routes/woreda.credentials'
import { Route as WoredaDashboardRouteImport } from './routes/woreda.dashboard'
import { Route as WoredaHouseholdsRouteImport } from './routes/woreda.households'
import { Route as WoredaReportsRouteImport } from './routes/woreda.reports'
import { Route as WoredaResidentsRouteImport } from './routes/woreda.residents'
import { Route as WoredaRevenueRouteImport } from './routes/woreda.revenue'
import { Route as WoredaServicesRouteImport } from './routes/woreda.services'
import { Route as WoredaSettingsRouteImport } from './routes/woreda.settings'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as VerifyLetterTokenRouteImport } from './routes/verify.letter.$token'
import { Route as VerifyReceiptTokenRouteImport } from './routes/verify.receipt.$token'
import { Route as WoredaCivilIndexRouteImport } from './routes/woreda.civil.index'
import { Route as WoredaCivilEventIdRouteImport } from './routes/woreda.civil.$eventId'
import { Route as WoredaCredentialsIndexRouteImport } from './routes/woreda.credentials.index'
import { Route as WoredaCredentialsNewRouteImport } from './routes/woreda.credentials.new'
import { Route as WoredaCredentialsVerifyRouteImport } from './routes/woreda.credentials.verify'
import { Route as WoredaHouseholdsIndexRouteImport } from './routes/woreda.households.index'
import { Route as WoredaHouseholdsNewRouteImport } from './routes/woreda.households.new'
import { Route as WoredaRentalHousesIndexRouteImport } from './routes/woreda.rental-houses.index'
import { Route as WoredaRentalHousesNewRouteImport } from './routes/woreda.rental-houses.new'
import { Route as WoredaResidentsIndexRouteImport } from './routes/woreda.residents.index'
import { Route as WoredaResidentsNewRouteImport } from './routes/woreda.residents.new'
import { Route as WoredaRevenueIndexRouteImport } from './routes/woreda.revenue.index'
import { Route as WoredaServicesIndexRouteImport } from './routes/woreda.services.index'
import { Route as WoredaServicesNewRouteImport } from './routes/woreda.services.new'
import { Route as AdminTenantsWoredaIdIndexRouteImport } from './routes/admin.tenants.$woredaId.index'
import { Route as AdminTenantsWoredaIdProvisionRouteImport } from './routes/admin.tenants.$woredaId.provision'
import { Route as WoredaCivilBirthNewRouteImport } from './routes/woreda.civil.birth.new'
import { Route as WoredaCivilDeathNewRouteImport } from './routes/woreda.civil.death.new'
import { Route as WoredaCivilDivorceNewRouteImport } from './routes/woreda.civil.divorce.new'
import { Route as WoredaCivilMarriageNewRouteImport } from './routes/woreda.civil.marriage.new'
import { Route as WoredaCredentialsRequestIdIndexRouteImport } from './routes/woreda.credentials.$requestId.index'
import { Route as WoredaCredentialsRequestIdPrintRouteImport } from './routes/woreda.credentials.$requestId.print'
import { Route as WoredaHouseholdsHouseholdIdIndexRouteImport } from './routes/woreda.households.$householdId.index'
import { Route as WoredaHouseholdsHouseholdIdEditRouteImport } from './routes/woreda.households.$householdId.edit'
import { Route as WoredaRentalHousesHouseIdIndexRouteImport } from './routes/woreda.rental-houses.$houseId.index'
import { Route as WoredaRentalHousesHouseIdEditRouteImport } from './routes/woreda.rental-houses.$houseId.edit'
import { Route as WoredaRentalHousesOccupantsNewRouteImport } from './routes/woreda.rental-houses.occupants.new'
import { Route as WoredaRentalHousesRequestsIndexRouteImport } from './routes/woreda.rental-houses.requests.index'
import { Route as WoredaResidentsResidentIdIndexRouteImport } from './routes/woreda.residents.$residentId.index'
import { Route as WoredaResidentsResidentIdEditRouteImport } from './routes/woreda.residents.$residentId.edit'
import { Route as WoredaRevenuePaymentIdReceiptRouteImport } from './routes/woreda.revenue.$paymentId.receipt'
import { Route as WoredaServicesRequestIdIndexRouteImport } from './routes/woreda.services.$requestId.index'
import { Route as WoredaServicesRequestIdPrintRouteImport } from './routes/woreda.services.$requestId.print'
import { Route as WoredaRentalHousesRequestsRequestIdIndexRouteImport } from './routes/woreda.rental-houses.requests.$requestId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WoredaRoute = WoredaRouteImport.update({
  id: '/woreda',
  path: '/woreda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsoleRolesRoute = AdminConsoleRolesRouteImport.update({
  id: '/console-roles',
  path: '/console-roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCredentialTemplateRoute = AdminCredentialTemplateRouteImport.update({
  id: '/credential-template',
  path: '/credential-template',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const VTokenRoute = VTokenRouteImport.update({
  id: '/v/$token',
  path: '/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WoredaApprovalsRoute = WoredaApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaAuditRoute = WoredaAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaCivilRoute = WoredaCivilRouteImport.update({
  id: '/civil',
  path: '/civil',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaComplaintsRoute = WoredaComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaCredentialsRoute = WoredaCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaDashboardRoute = WoredaDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaHouseholdsRoute = WoredaHouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaReportsRoute = WoredaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaResidentsRoute = WoredaResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaRevenueRoute = WoredaRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaServicesRoute = WoredaServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaSettingsRoute = WoredaSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WoredaRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const VerifyLetterTokenRoute = VerifyLetterTokenRouteImport.update({
  id: '/verify/letter/$token',
  path: '/verify/letter/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReceiptTokenRoute = VerifyReceiptTokenRouteImport.update({
  id: '/verify/receipt/$token',
  path: '/verify/receipt/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WoredaCivilIndexRoute = WoredaCivilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCivilEventIdRoute = WoredaCivilEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCredentialsIndexRoute = WoredaCredentialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaCredentialsRoute,
} as any)
const WoredaCredentialsNewRoute = WoredaCredentialsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WoredaCredentialsRoute,
} as any)
const WoredaCredentialsVerifyRoute = WoredaCredentialsVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => WoredaCredentialsRoute,
} as any)
const WoredaHouseholdsIndexRoute = WoredaHouseholdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaHouseholdsRoute,
} as any)
const WoredaHouseholdsNewRoute = WoredaHouseholdsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WoredaHouseholdsRoute,
} as any)
const WoredaRentalHousesIndexRoute = WoredaRentalHousesIndexRouteImport.update({
  id: '/rental-houses/',
  path: '/rental-houses/',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaRentalHousesNewRoute = WoredaRentalHousesNewRouteImport.update({
  id: '/rental-houses/new',
  path: '/rental-houses/new',
  getParentRoute: () => WoredaRoute,
} as any)
const WoredaResidentsIndexRoute = WoredaResidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaResidentsRoute,
} as any)
const WoredaResidentsNewRoute = WoredaResidentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WoredaResidentsRoute,
} as any)
const WoredaRevenueIndexRoute = WoredaRevenueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaRevenueRoute,
} as any)
const WoredaServicesIndexRoute = WoredaServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WoredaServicesRoute,
} as any)
const WoredaServicesNewRoute = WoredaServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WoredaServicesRoute,
} as any)
const AdminTenantsWoredaIdIndexRoute =
  AdminTenantsWoredaIdIndexRouteImport.update({
    id: '/tenants/$woredaId/',
    path: '/tenants/$woredaId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTenantsWoredaIdProvisionRoute =
  AdminTenantsWoredaIdProvisionRouteImport.update({
    id: '/tenants/$woredaId/provision',
    path: '/tenants/$woredaId/provision',
    getParentRoute: () => AdminRoute,
  } as any)
const WoredaCivilBirthNewRoute = WoredaCivilBirthNewRouteImport.update({
  id: '/birth/new',
  path: '/birth/new',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCivilDeathNewRoute = WoredaCivilDeathNewRouteImport.update({
  id: '/death/new',
  path: '/death/new',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCivilDivorceNewRoute = WoredaCivilDivorceNewRouteImport.update({
  id: '/divorce/new',
  path: '/divorce/new',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCivilMarriageNewRoute = WoredaCivilMarriageNewRouteImport.update({
  id: '/marriage/new',
  path: '/marriage/new',
  getParentRoute: () => WoredaCivilRoute,
} as any)
const WoredaCredentialsRequestIdIndexRoute =
  WoredaCredentialsRequestIdIndexRouteImport.update({
    id: '/$requestId/',
    path: '/$requestId/',
    getParentRoute: () => WoredaCredentialsRoute,
  } as any)
const WoredaCredentialsRequestIdPrintRoute =
  WoredaCredentialsRequestIdPrintRouteImport.update({
    id: '/$requestId/print',
    path: '/$requestId/print',
    getParentRoute: () => WoredaCredentialsRoute,
  } as any)
const WoredaHouseholdsHouseholdIdIndexRoute =
  WoredaHouseholdsHouseholdIdIndexRouteImport.update({
    id: '/$householdId/',
    path: '/$householdId/',
    getParentRoute: () => WoredaHouseholdsRoute,
  } as any)
const WoredaHouseholdsHouseholdIdEditRoute =
  WoredaHouseholdsHouseholdIdEditRouteImport.update({
    id: '/$householdId/edit',
    path: '/$householdId/edit',
    getParentRoute: () => WoredaHouseholdsRoute,
  } as any)
const WoredaRentalHousesHouseIdIndexRoute =
  WoredaRentalHousesHouseIdIndexRouteImport.update({
    id: '/rental-houses/$houseId/',
    path: '/rental-houses/$houseId/',
    getParentRoute: () => WoredaRoute,
  } as any)
const WoredaRentalHousesHouseIdEditRoute =
  WoredaRentalHousesHouseIdEditRouteImport.update({
    id: '/rental-houses/$houseId/edit',
    path: '/rental-houses/$houseId/edit',
    getParentRoute: () => WoredaRoute,
  } as any)
const WoredaRentalHousesOccupantsNewRoute =
  WoredaRentalHousesOccupantsNewRouteImport.update({
    id: '/rental-houses/occupants/new',
    path: '/rental-houses/occupants/new',
    getParentRoute: () => WoredaRoute,
  } as any)
const WoredaRentalHousesRequestsIndexRoute =
  WoredaRentalHousesRequestsIndexRouteImport.update({
    id: '/rental-houses/requests/',
    path: '/rental-houses/requests/',
    getParentRoute: () => WoredaRoute,
  } as any)
const WoredaResidentsResidentIdIndexRoute =
  WoredaResidentsResidentIdIndexRouteImport.update({
    id: '/$residentId/',
    path: '/$residentId/',
    getParentRoute: () => WoredaResidentsRoute,
  } as any)
const WoredaResidentsResidentIdEditRoute =
  WoredaResidentsResidentIdEditRouteImport.update({
    id: '/$residentId/edit',
    path: '/$residentId/edit',
    getParentRoute: () => WoredaResidentsRoute,
  } as any)
const WoredaRevenuePaymentIdReceiptRoute =
  WoredaRevenuePaymentIdReceiptRouteImport.update({
    id: '/$paymentId/receipt',
    path: '/$paymentId/receipt',
    getParentRoute: () => WoredaRevenueRoute,
  } as any)
const WoredaServicesRequestIdIndexRoute =
  WoredaServicesRequestIdIndexRouteImport.update({
    id: '/$requestId/',
    path: '/$requestId/',
    getParentRoute: () => WoredaServicesRoute,
  } as any)
const WoredaServicesRequestIdPrintRoute =
  WoredaServicesRequestIdPrintRouteImport.update({
    id: '/$requestId/print',
    path: '/$requestId/print',
    getParentRoute: () => WoredaServicesRoute,
  } as any)
const WoredaRentalHousesRequestsRequestIdIndexRoute =
  WoredaRentalHousesRequestsRequestIdIndexRouteImport.update({
    id: '/rental-houses/requests/$requestId/',
    path: '/rental-houses/requests/$requestId/',
    getParentRoute: () => WoredaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/woreda': typeof WoredaRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/console-roles': typeof AdminConsoleRolesRoute
  '/admin/credential-template': typeof AdminCredentialTemplateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/v/$token': typeof VTokenRoute
  '/woreda/approvals': typeof WoredaApprovalsRoute
  '/woreda/audit': typeof WoredaAuditRoute
  '/woreda/civil': typeof WoredaCivilRouteWithChildren
  '/woreda/complaints': typeof WoredaComplaintsRoute
  '/woreda/credentials': typeof WoredaCredentialsRouteWithChildren
  '/woreda/dashboard': typeof WoredaDashboardRoute
  '/woreda/households': typeof WoredaHouseholdsRouteWithChildren
  '/woreda/reports': typeof WoredaReportsRoute
  '/woreda/residents': typeof WoredaResidentsRouteWithChildren
  '/woreda/revenue': typeof WoredaRevenueRouteWithChildren
  '/woreda/services': typeof WoredaServicesRouteWithChildren
  '/woreda/settings': typeof WoredaSettingsRoute
  '/verify/letter/$token': typeof VerifyLetterTokenRoute
  '/verify/receipt/$token': typeof VerifyReceiptTokenRoute
  '/woreda/civil/$eventId': typeof WoredaCivilEventIdRoute
  '/woreda/credentials/new': typeof WoredaCredentialsNewRoute
  '/woreda/credentials/verify': typeof WoredaCredentialsVerifyRoute
  '/woreda/households/new': typeof WoredaHouseholdsNewRoute
  '/woreda/rental-houses/new': typeof WoredaRentalHousesNewRoute
  '/woreda/residents/new': typeof WoredaResidentsNewRoute
  '/woreda/services/new': typeof WoredaServicesNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/woreda/civil/': typeof WoredaCivilIndexRoute
  '/woreda/credentials/': typeof WoredaCredentialsIndexRoute
  '/woreda/households/': typeof WoredaHouseholdsIndexRoute
  '/woreda/rental-houses/': typeof WoredaRentalHousesIndexRoute
  '/woreda/residents/': typeof WoredaResidentsIndexRoute
  '/woreda/revenue/': typeof WoredaRevenueIndexRoute
  '/woreda/services/': typeof WoredaServicesIndexRoute
  '/admin/tenants/$woredaId/provision': typeof AdminTenantsWoredaIdProvisionRoute
  '/woreda/civil/birth/new': typeof WoredaCivilBirthNewRoute
  '/woreda/civil/death/new': typeof WoredaCivilDeathNewRoute
  '/woreda/civil/divorce/new': typeof WoredaCivilDivorceNewRoute
  '/woreda/civil/marriage/new': typeof WoredaCivilMarriageNewRoute
  '/woreda/credentials/$requestId/print': typeof WoredaCredentialsRequestIdPrintRoute
  '/woreda/households/$householdId/edit': typeof WoredaHouseholdsHouseholdIdEditRoute
  '/woreda/rental-houses/$houseId/edit': typeof WoredaRentalHousesHouseIdEditRoute
  '/woreda/rental-houses/occupants/new': typeof WoredaRentalHousesOccupantsNewRoute
  '/woreda/residents/$residentId/edit': typeof WoredaResidentsResidentIdEditRoute
  '/woreda/revenue/$paymentId/receipt': typeof WoredaRevenuePaymentIdReceiptRoute
  '/woreda/services/$requestId/print': typeof WoredaServicesRequestIdPrintRoute
  '/admin/tenants/$woredaId/': typeof AdminTenantsWoredaIdIndexRoute
  '/woreda/credentials/$requestId/': typeof WoredaCredentialsRequestIdIndexRoute
  '/woreda/households/$householdId/': typeof WoredaHouseholdsHouseholdIdIndexRoute
  '/woreda/rental-houses/$houseId/': typeof WoredaRentalHousesHouseIdIndexRoute
  '/woreda/rental-houses/requests/': typeof WoredaRentalHousesRequestsIndexRoute
  '/woreda/residents/$residentId/': typeof WoredaResidentsResidentIdIndexRoute
  '/woreda/services/$requestId/': typeof WoredaServicesRequestIdIndexRoute
  '/woreda/rental-houses/requests/$requestId/': typeof WoredaRentalHousesRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/woreda': typeof WoredaRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/console-roles': typeof AdminConsoleRolesRoute
  '/admin/credential-template': typeof AdminCredentialTemplateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/v/$token': typeof VTokenRoute
  '/woreda/approvals': typeof WoredaApprovalsRoute
  '/woreda/audit': typeof WoredaAuditRoute
  '/woreda/complaints': typeof WoredaComplaintsRoute
  '/woreda/dashboard': typeof WoredaDashboardRoute
  '/woreda/reports': typeof WoredaReportsRoute
  '/woreda/settings': typeof WoredaSettingsRoute
  '/verify/letter/$token': typeof VerifyLetterTokenRoute
  '/verify/receipt/$token': typeof VerifyReceiptTokenRoute
  '/woreda/civil/$eventId': typeof WoredaCivilEventIdRoute
  '/woreda/credentials/new': typeof WoredaCredentialsNewRoute
  '/woreda/credentials/verify': typeof WoredaCredentialsVerifyRoute
  '/woreda/households/new': typeof WoredaHouseholdsNewRoute
  '/woreda/rental-houses/new': typeof WoredaRentalHousesNewRoute
  '/woreda/residents/new': typeof WoredaResidentsNewRoute
  '/woreda/services/new': typeof WoredaServicesNewRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/woreda/civil': typeof WoredaCivilIndexRoute
  '/woreda/credentials': typeof WoredaCredentialsIndexRoute
  '/woreda/households': typeof WoredaHouseholdsIndexRoute
  '/woreda/rental-houses': typeof WoredaRentalHousesIndexRoute
  '/woreda/residents': typeof WoredaResidentsIndexRoute
  '/woreda/revenue': typeof WoredaRevenueIndexRoute
  '/woreda/services': typeof WoredaServicesIndexRoute
  '/admin/tenants/$woredaId/provision': typeof AdminTenantsWoredaIdProvisionRoute
  '/woreda/civil/birth/new': typeof WoredaCivilBirthNewRoute
  '/woreda/civil/death/new': typeof WoredaCivilDeathNewRoute
  '/woreda/civil/divorce/new': typeof WoredaCivilDivorceNewRoute
  '/woreda/civil/marriage/new': typeof WoredaCivilMarriageNewRoute
  '/woreda/credentials/$requestId/print': typeof WoredaCredentialsRequestIdPrintRoute
  '/woreda/households/$householdId/edit': typeof WoredaHouseholdsHouseholdIdEditRoute
  '/woreda/rental-houses/$houseId/edit': typeof WoredaRentalHousesHouseIdEditRoute
  '/woreda/rental-houses/occupants/new': typeof WoredaRentalHousesOccupantsNewRoute
  '/woreda/residents/$residentId/edit': typeof WoredaResidentsResidentIdEditRoute
  '/woreda/revenue/$paymentId/receipt': typeof WoredaRevenuePaymentIdReceiptRoute
  '/woreda/services/$requestId/print': typeof WoredaServicesRequestIdPrintRoute
  '/admin/tenants/$woredaId': typeof AdminTenantsWoredaIdIndexRoute
  '/woreda/credentials/$requestId': typeof WoredaCredentialsRequestIdIndexRoute
  '/woreda/households/$householdId': typeof WoredaHouseholdsHouseholdIdIndexRoute
  '/woreda/rental-houses/$houseId': typeof WoredaRentalHousesHouseIdIndexRoute
  '/woreda/rental-houses/requests': typeof WoredaRentalHousesRequestsIndexRoute
  '/woreda/residents/$residentId': typeof WoredaResidentsResidentIdIndexRoute
  '/woreda/services/$requestId': typeof WoredaServicesRequestIdIndexRoute
  '/woreda/rental-houses/requests/$requestId': typeof WoredaRentalHousesRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/woreda': typeof WoredaRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/console-roles': typeof AdminConsoleRolesRoute
  '/admin/credential-template': typeof AdminCredentialTemplateRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/v/$token': typeof VTokenRoute
  '/woreda/approvals': typeof WoredaApprovalsRoute
  '/woreda/audit': typeof WoredaAuditRoute
  '/woreda/civil': typeof WoredaCivilRouteWithChildren
  '/woreda/complaints': typeof WoredaComplaintsRoute
  '/woreda/credentials': typeof WoredaCredentialsRouteWithChildren
  '/woreda/dashboard': typeof WoredaDashboardRoute
  '/woreda/households': typeof WoredaHouseholdsRouteWithChildren
  '/woreda/reports': typeof WoredaReportsRoute
  '/woreda/residents': typeof WoredaResidentsRouteWithChildren
  '/woreda/revenue': typeof WoredaRevenueRouteWithChildren
  '/woreda/services': typeof WoredaServicesRouteWithChildren
  '/woreda/settings': typeof WoredaSettingsRoute
  '/verify/letter/$token': typeof VerifyLetterTokenRoute
  '/verify/receipt/$token': typeof VerifyReceiptTokenRoute
  '/woreda/civil/$eventId': typeof WoredaCivilEventIdRoute
  '/woreda/credentials/new': typeof WoredaCredentialsNewRoute
  '/woreda/credentials/verify': typeof WoredaCredentialsVerifyRoute
  '/woreda/households/new': typeof WoredaHouseholdsNewRoute
  '/woreda/rental-houses/new': typeof WoredaRentalHousesNewRoute
  '/woreda/residents/new': typeof WoredaResidentsNewRoute
  '/woreda/services/new': typeof WoredaServicesNewRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/woreda/civil/': typeof WoredaCivilIndexRoute
  '/woreda/credentials/': typeof WoredaCredentialsIndexRoute
  '/woreda/households/': typeof WoredaHouseholdsIndexRoute
  '/woreda/rental-houses/': typeof WoredaRentalHousesIndexRoute
  '/woreda/residents/': typeof WoredaResidentsIndexRoute
  '/woreda/revenue/': typeof WoredaRevenueIndexRoute
  '/woreda/services/': typeof WoredaServicesIndexRoute
  '/admin/tenants/$woredaId/provision': typeof AdminTenantsWoredaIdProvisionRoute
  '/woreda/civil/birth/new': typeof WoredaCivilBirthNewRoute
  '/woreda/civil/death/new': typeof WoredaCivilDeathNewRoute
  '/woreda/civil/divorce/new': typeof WoredaCivilDivorceNewRoute
  '/woreda/civil/marriage/new': typeof WoredaCivilMarriageNewRoute
  '/woreda/credentials/$requestId/print': typeof WoredaCredentialsRequestIdPrintRoute
  '/woreda/households/$householdId/edit': typeof WoredaHouseholdsHouseholdIdEditRoute
  '/woreda/rental-houses/$houseId/edit': typeof WoredaRentalHousesHouseIdEditRoute
  '/woreda/rental-houses/occupants/new': typeof WoredaRentalHousesOccupantsNewRoute
  '/woreda/residents/$residentId/edit': typeof WoredaResidentsResidentIdEditRoute
  '/woreda/revenue/$paymentId/receipt': typeof WoredaRevenuePaymentIdReceiptRoute
  '/woreda/services/$requestId/print': typeof WoredaServicesRequestIdPrintRoute
  '/admin/tenants/$woredaId/': typeof AdminTenantsWoredaIdIndexRoute
  '/woreda/credentials/$requestId/': typeof WoredaCredentialsRequestIdIndexRoute
  '/woreda/households/$householdId/': typeof WoredaHouseholdsHouseholdIdIndexRoute
  '/woreda/rental-houses/$houseId/': typeof WoredaRentalHousesHouseIdIndexRoute
  '/woreda/rental-houses/requests/': typeof WoredaRentalHousesRequestsIndexRoute
  '/woreda/residents/$residentId/': typeof WoredaResidentsResidentIdIndexRoute
  '/woreda/services/$requestId/': typeof WoredaServicesRequestIdIndexRoute
  '/woreda/rental-houses/requests/$requestId/': typeof WoredaRentalHousesRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/set-password'
    | '/woreda'
    | '/admin/audit'
    | '/admin/console-roles'
    | '/admin/credential-template'
    | '/admin/dashboard'
    | '/v/$token'
    | '/woreda/approvals'
    | '/woreda/audit'
    | '/woreda/civil'
    | '/woreda/complaints'
    | '/woreda/credentials'
    | '/woreda/dashboard'
    | '/woreda/households'
    | '/woreda/reports'
    | '/woreda/residents'
    | '/woreda/revenue'
    | '/woreda/services'
    | '/woreda/settings'
    | '/verify/letter/$token'
    | '/verify/receipt/$token'
    | '/woreda/civil/$eventId'
    | '/woreda/credentials/new'
    | '/woreda/credentials/verify'
    | '/woreda/households/new'
    | '/woreda/rental-houses/new'
    | '/woreda/residents/new'
    | '/woreda/services/new'
    | '/admin/tenants/'
    | '/woreda/civil/'
    | '/woreda/credentials/'
    | '/woreda/households/'
    | '/woreda/rental-houses/'
    | '/woreda/residents/'
    | '/woreda/revenue/'
    | '/woreda/services/'
    | '/admin/tenants/$woredaId/provision'
    | '/woreda/civil/birth/new'
    | '/woreda/civil/death/new'
    | '/woreda/civil/divorce/new'
    | '/woreda/civil/marriage/new'
    | '/woreda/credentials/$requestId/print'
    | '/woreda/households/$householdId/edit'
    | '/woreda/rental-houses/$houseId/edit'
    | '/woreda/rental-houses/occupants/new'
    | '/woreda/residents/$residentId/edit'
    | '/woreda/revenue/$paymentId/receipt'
    | '/woreda/services/$requestId/print'
    | '/admin/tenants/$woredaId/'
    | '/woreda/credentials/$requestId/'
    | '/woreda/households/$householdId/'
    | '/woreda/rental-houses/$houseId/'
    | '/woreda/rental-houses/requests/'
    | '/woreda/residents/$residentId/'
    | '/woreda/services/$requestId/'
    | '/woreda/rental-houses/requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/set-password'
    | '/woreda'
    | '/admin/audit'
    | '/admin/console-roles'
    | '/admin/credential-template'
    | '/admin/dashboard'
    | '/v/$token'
    | '/woreda/approvals'
    | '/woreda/audit'
    | '/woreda/complaints'
    | '/woreda/dashboard'
    | '/woreda/reports'
    | '/woreda/settings'
    | '/verify/letter/$token'
    | '/verify/receipt/$token'
    | '/woreda/civil/$eventId'
    | '/woreda/credentials/new'
    | '/woreda/credentials/verify'
    | '/woreda/households/new'
    | '/woreda/rental-houses/new'
    | '/woreda/residents/new'
    | '/woreda/services/new'
    | '/admin/tenants'
    | '/woreda/civil'
    | '/woreda/credentials'
    | '/woreda/households'
    | '/woreda/rental-houses'
    | '/woreda/residents'
    | '/woreda/revenue'
    | '/woreda/services'
    | '/admin/tenants/$woredaId/provision'
    | '/woreda/civil/birth/new'
    | '/woreda/civil/death/new'
    | '/woreda/civil/divorce/new'
    | '/woreda/civil/marriage/new'
    | '/woreda/credentials/$requestId/print'
    | '/woreda/households/$householdId/edit'
    | '/woreda/rental-houses/$houseId/edit'
    | '/woreda/rental-houses/occupants/new'
    | '/woreda/residents/$residentId/edit'
    | '/woreda/revenue/$paymentId/receipt'
    | '/woreda/services/$requestId/print'
    | '/admin/tenants/$woredaId'
    | '/woreda/credentials/$requestId'
    | '/woreda/households/$householdId'
    | '/woreda/rental-houses/$houseId'
    | '/woreda/rental-houses/requests'
    | '/woreda/residents/$residentId'
    | '/woreda/services/$requestId'
    | '/woreda/rental-houses/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/set-password'
    | '/woreda'
    | '/admin/audit'
    | '/admin/console-roles'
    | '/admin/credential-template'
    | '/admin/dashboard'
    | '/v/$token'
    | '/woreda/approvals'
    | '/woreda/audit'
    | '/woreda/civil'
    | '/woreda/complaints'
    | '/woreda/credentials'
    | '/woreda/dashboard'
    | '/woreda/households'
    | '/woreda/reports'
    | '/woreda/residents'
    | '/woreda/revenue'
    | '/woreda/services'
    | '/woreda/settings'
    | '/verify/letter/$token'
    | '/verify/receipt/$token'
    | '/woreda/civil/$eventId'
    | '/woreda/credentials/new'
    | '/woreda/credentials/verify'
    | '/woreda/households/new'
    | '/woreda/rental-houses/new'
    | '/woreda/residents/new'
    | '/woreda/services/new'
    | '/admin/tenants/'
    | '/woreda/civil/'
    | '/woreda/credentials/'
    | '/woreda/households/'
    | '/woreda/rental-houses/'
    | '/woreda/residents/'
    | '/woreda/revenue/'
    | '/woreda/services/'
    | '/admin/tenants/$woredaId/provision'
    | '/woreda/civil/birth/new'
    | '/woreda/civil/death/new'
    | '/woreda/civil/divorce/new'
    | '/woreda/civil/marriage/new'
    | '/woreda/credentials/$requestId/print'
    | '/woreda/households/$householdId/edit'
    | '/woreda/rental-houses/$houseId/edit'
    | '/woreda/rental-houses/occupants/new'
    | '/woreda/residents/$residentId/edit'
    | '/woreda/revenue/$paymentId/receipt'
    | '/woreda/services/$requestId/print'
    | '/admin/tenants/$woredaId/'
    | '/woreda/credentials/$requestId/'
    | '/woreda/households/$householdId/'
    | '/woreda/rental-houses/$houseId/'
    | '/woreda/rental-houses/requests/'
    | '/woreda/residents/$residentId/'
    | '/woreda/services/$requestId/'
    | '/woreda/rental-houses/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  WoredaRoute: typeof WoredaRouteWithChildren
  VTokenRoute: typeof VTokenRoute
  VerifyLetterTokenRoute: typeof VerifyLetterTokenRoute
  VerifyReceiptTokenRoute: typeof VerifyReceiptTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/woreda': {
      id: '/woreda'
      path: '/woreda'
      fullPath: '/woreda'
      preLoaderRoute: typeof WoredaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/console-roles': {
      id: '/admin/console-roles'
      path: '/console-roles'
      fullPath: '/admin/console-roles'
      preLoaderRoute: typeof AdminConsoleRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credential-template': {
      id: '/admin/credential-template'
      path: '/credential-template'
      fullPath: '/admin/credential-template'
      preLoaderRoute: typeof AdminCredentialTemplateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/v/$token': {
      id: '/v/$token'
      path: '/v/$token'
      fullPath: '/v/$token'
      preLoaderRoute: typeof VTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/woreda/approvals': {
      id: '/woreda/approvals'
      path: '/approvals'
      fullPath: '/woreda/approvals'
      preLoaderRoute: typeof WoredaApprovalsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/audit': {
      id: '/woreda/audit'
      path: '/audit'
      fullPath: '/woreda/audit'
      preLoaderRoute: typeof WoredaAuditRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/civil': {
      id: '/woreda/civil'
      path: '/civil'
      fullPath: '/woreda/civil'
      preLoaderRoute: typeof WoredaCivilRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/complaints': {
      id: '/woreda/complaints'
      path: '/complaints'
      fullPath: '/woreda/complaints'
      preLoaderRoute: typeof WoredaComplaintsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/credentials': {
      id: '/woreda/credentials'
      path: '/credentials'
      fullPath: '/woreda/credentials'
      preLoaderRoute: typeof WoredaCredentialsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/dashboard': {
      id: '/woreda/dashboard'
      path: '/dashboard'
      fullPath: '/woreda/dashboard'
      preLoaderRoute: typeof WoredaDashboardRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/households': {
      id: '/woreda/households'
      path: '/households'
      fullPath: '/woreda/households'
      preLoaderRoute: typeof WoredaHouseholdsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/reports': {
      id: '/woreda/reports'
      path: '/reports'
      fullPath: '/woreda/reports'
      preLoaderRoute: typeof WoredaReportsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/residents': {
      id: '/woreda/residents'
      path: '/residents'
      fullPath: '/woreda/residents'
      preLoaderRoute: typeof WoredaResidentsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/revenue': {
      id: '/woreda/revenue'
      path: '/revenue'
      fullPath: '/woreda/revenue'
      preLoaderRoute: typeof WoredaRevenueRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/services': {
      id: '/woreda/services'
      path: '/services'
      fullPath: '/woreda/services'
      preLoaderRoute: typeof WoredaServicesRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/settings': {
      id: '/woreda/settings'
      path: '/settings'
      fullPath: '/woreda/settings'
      preLoaderRoute: typeof WoredaSettingsRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/verify/letter/$token': {
      id: '/verify/letter/$token'
      path: '/verify/letter/$token'
      fullPath: '/verify/letter/$token'
      preLoaderRoute: typeof VerifyLetterTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/receipt/$token': {
      id: '/verify/receipt/$token'
      path: '/verify/receipt/$token'
      fullPath: '/verify/receipt/$token'
      preLoaderRoute: typeof VerifyReceiptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/woreda/civil/': {
      id: '/woreda/civil/'
      path: '/'
      fullPath: '/woreda/civil/'
      preLoaderRoute: typeof WoredaCivilIndexRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/civil/$eventId': {
      id: '/woreda/civil/$eventId'
      path: '/$eventId'
      fullPath: '/woreda/civil/$eventId'
      preLoaderRoute: typeof WoredaCivilEventIdRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/credentials/': {
      id: '/woreda/credentials/'
      path: '/'
      fullPath: '/woreda/credentials/'
      preLoaderRoute: typeof WoredaCredentialsIndexRouteImport
      parentRoute: typeof WoredaCredentialsRoute
    }
    '/woreda/credentials/new': {
      id: '/woreda/credentials/new'
      path: '/new'
      fullPath: '/woreda/credentials/new'
      preLoaderRoute: typeof WoredaCredentialsNewRouteImport
      parentRoute: typeof WoredaCredentialsRoute
    }
    '/woreda/credentials/verify': {
      id: '/woreda/credentials/verify'
      path: '/verify'
      fullPath: '/woreda/credentials/verify'
      preLoaderRoute: typeof WoredaCredentialsVerifyRouteImport
      parentRoute: typeof WoredaCredentialsRoute
    }
    '/woreda/households/': {
      id: '/woreda/households/'
      path: '/'
      fullPath: '/woreda/households/'
      preLoaderRoute: typeof WoredaHouseholdsIndexRouteImport
      parentRoute: typeof WoredaHouseholdsRoute
    }
    '/woreda/households/new': {
      id: '/woreda/households/new'
      path: '/new'
      fullPath: '/woreda/households/new'
      preLoaderRoute: typeof WoredaHouseholdsNewRouteImport
      parentRoute: typeof WoredaHouseholdsRoute
    }
    '/woreda/rental-houses/': {
      id: '/woreda/rental-houses/'
      path: '/rental-houses'
      fullPath: '/woreda/rental-houses/'
      preLoaderRoute: typeof WoredaRentalHousesIndexRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/rental-houses/new': {
      id: '/woreda/rental-houses/new'
      path: '/rental-houses/new'
      fullPath: '/woreda/rental-houses/new'
      preLoaderRoute: typeof WoredaRentalHousesNewRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/residents/': {
      id: '/woreda/residents/'
      path: '/'
      fullPath: '/woreda/residents/'
      preLoaderRoute: typeof WoredaResidentsIndexRouteImport
      parentRoute: typeof WoredaResidentsRoute
    }
    '/woreda/residents/new': {
      id: '/woreda/residents/new'
      path: '/new'
      fullPath: '/woreda/residents/new'
      preLoaderRoute: typeof WoredaResidentsNewRouteImport
      parentRoute: typeof WoredaResidentsRoute
    }
    '/woreda/revenue/': {
      id: '/woreda/revenue/'
      path: '/'
      fullPath: '/woreda/revenue/'
      preLoaderRoute: typeof WoredaRevenueIndexRouteImport
      parentRoute: typeof WoredaRevenueRoute
    }
    '/woreda/services/': {
      id: '/woreda/services/'
      path: '/'
      fullPath: '/woreda/services/'
      preLoaderRoute: typeof WoredaServicesIndexRouteImport
      parentRoute: typeof WoredaServicesRoute
    }
    '/woreda/services/new': {
      id: '/woreda/services/new'
      path: '/new'
      fullPath: '/woreda/services/new'
      preLoaderRoute: typeof WoredaServicesNewRouteImport
      parentRoute: typeof WoredaServicesRoute
    }
    '/admin/tenants/$woredaId/': {
      id: '/admin/tenants/$woredaId/'
      path: '/tenants/$woredaId'
      fullPath: '/admin/tenants/$woredaId/'
      preLoaderRoute: typeof AdminTenantsWoredaIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$woredaId/provision': {
      id: '/admin/tenants/$woredaId/provision'
      path: '/tenants/$woredaId/provision'
      fullPath: '/admin/tenants/$woredaId/provision'
      preLoaderRoute: typeof AdminTenantsWoredaIdProvisionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/woreda/civil/birth/new': {
      id: '/woreda/civil/birth/new'
      path: '/birth/new'
      fullPath: '/woreda/civil/birth/new'
      preLoaderRoute: typeof WoredaCivilBirthNewRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/civil/death/new': {
      id: '/woreda/civil/death/new'
      path: '/death/new'
      fullPath: '/woreda/civil/death/new'
      preLoaderRoute: typeof WoredaCivilDeathNewRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/civil/divorce/new': {
      id: '/woreda/civil/divorce/new'
      path: '/divorce/new'
      fullPath: '/woreda/civil/divorce/new'
      preLoaderRoute: typeof WoredaCivilDivorceNewRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/civil/marriage/new': {
      id: '/woreda/civil/marriage/new'
      path: '/marriage/new'
      fullPath: '/woreda/civil/marriage/new'
      preLoaderRoute: typeof WoredaCivilMarriageNewRouteImport
      parentRoute: typeof WoredaCivilRoute
    }
    '/woreda/credentials/$requestId/': {
      id: '/woreda/credentials/$requestId/'
      path: '/$requestId'
      fullPath: '/woreda/credentials/$requestId/'
      preLoaderRoute: typeof WoredaCredentialsRequestIdIndexRouteImport
      parentRoute: typeof WoredaCredentialsRoute
    }
    '/woreda/credentials/$requestId/print': {
      id: '/woreda/credentials/$requestId/print'
      path: '/$requestId/print'
      fullPath: '/woreda/credentials/$requestId/print'
      preLoaderRoute: typeof WoredaCredentialsRequestIdPrintRouteImport
      parentRoute: typeof WoredaCredentialsRoute
    }
    '/woreda/households/$householdId/': {
      id: '/woreda/households/$householdId/'
      path: '/$householdId'
      fullPath: '/woreda/households/$householdId/'
      preLoaderRoute: typeof WoredaHouseholdsHouseholdIdIndexRouteImport
      parentRoute: typeof WoredaHouseholdsRoute
    }
    '/woreda/households/$householdId/edit': {
      id: '/woreda/households/$householdId/edit'
      path: '/$householdId/edit'
      fullPath: '/woreda/households/$householdId/edit'
      preLoaderRoute: typeof WoredaHouseholdsHouseholdIdEditRouteImport
      parentRoute: typeof WoredaHouseholdsRoute
    }
    '/woreda/rental-houses/$houseId/': {
      id: '/woreda/rental-houses/$houseId/'
      path: '/rental-houses/$houseId'
      fullPath: '/woreda/rental-houses/$houseId/'
      preLoaderRoute: typeof WoredaRentalHousesHouseIdIndexRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/rental-houses/$houseId/edit': {
      id: '/woreda/rental-houses/$houseId/edit'
      path: '/rental-houses/$houseId/edit'
      fullPath: '/woreda/rental-houses/$houseId/edit'
      preLoaderRoute: typeof WoredaRentalHousesHouseIdEditRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/rental-houses/occupants/new': {
      id: '/woreda/rental-houses/occupants/new'
      path: '/rental-houses/occupants/new'
      fullPath: '/woreda/rental-houses/occupants/new'
      preLoaderRoute: typeof WoredaRentalHousesOccupantsNewRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/rental-houses/requests/': {
      id: '/woreda/rental-houses/requests/'
      path: '/rental-houses/requests'
      fullPath: '/woreda/rental-houses/requests/'
      preLoaderRoute: typeof WoredaRentalHousesRequestsIndexRouteImport
      parentRoute: typeof WoredaRoute
    }
    '/woreda/residents/$residentId/': {
      id: '/woreda/residents/$residentId/'
      path: '/$residentId'
      fullPath: '/woreda/residents/$residentId/'
      preLoaderRoute: typeof WoredaResidentsResidentIdIndexRouteImport
      parentRoute: typeof WoredaResidentsRoute
    }
    '/woreda/residents/$residentId/edit': {
      id: '/woreda/residents/$residentId/edit'
      path: '/$residentId/edit'
      fullPath: '/woreda/residents/$residentId/edit'
      preLoaderRoute: typeof WoredaResidentsResidentIdEditRouteImport
      parentRoute: typeof WoredaResidentsRoute
    }
    '/woreda/revenue/$paymentId/receipt': {
      id: '/woreda/revenue/$paymentId/receipt'
      path: '/$paymentId/receipt'
      fullPath: '/woreda/revenue/$paymentId/receipt'
      preLoaderRoute: typeof WoredaRevenuePaymentIdReceiptRouteImport
      parentRoute: typeof WoredaRevenueRoute
    }
    '/woreda/services/$requestId/': {
      id: '/woreda/services/$requestId/'
      path: '/$requestId'
      fullPath: '/woreda/services/$requestId/'
      preLoaderRoute: typeof WoredaServicesRequestIdIndexRouteImport
      parentRoute: typeof WoredaServicesRoute
    }
    '/woreda/services/$requestId/print': {
      id: '/woreda/services/$requestId/print'
      path: '/$requestId/print'
      fullPath: '/woreda/services/$requestId/print'
      preLoaderRoute: typeof WoredaServicesRequestIdPrintRouteImport
      parentRoute: typeof WoredaServicesRoute
    }
    '/woreda/rental-houses/requests/$requestId/': {
      id: '/woreda/rental-houses/requests/$requestId/'
      path: '/rental-houses/requests/$requestId'
      fullPath: '/woreda/rental-houses/requests/$requestId/'
      preLoaderRoute: typeof WoredaRentalHousesRequestsRequestIdIndexRouteImport
      parentRoute: typeof WoredaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminConsoleRolesRoute: typeof AdminConsoleRolesRoute
  AdminCredentialTemplateRoute: typeof AdminCredentialTemplateRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
  AdminTenantsWoredaIdProvisionRoute: typeof AdminTenantsWoredaIdProvisionRoute
  AdminTenantsWoredaIdIndexRoute: typeof AdminTenantsWoredaIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminConsoleRolesRoute: AdminConsoleRolesRoute,
  AdminCredentialTemplateRoute: AdminCredentialTemplateRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
  AdminTenantsWoredaIdProvisionRoute: AdminTenantsWoredaIdProvisionRoute,
  AdminTenantsWoredaIdIndexRoute: AdminTenantsWoredaIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WoredaCivilRouteChildren {
  WoredaCivilEventIdRoute: typeof WoredaCivilEventIdRoute
  WoredaCivilIndexRoute: typeof WoredaCivilIndexRoute
  WoredaCivilBirthNewRoute: typeof WoredaCivilBirthNewRoute
  WoredaCivilDeathNewRoute: typeof WoredaCivilDeathNewRoute
  WoredaCivilDivorceNewRoute: typeof WoredaCivilDivorceNewRoute
  WoredaCivilMarriageNewRoute: typeof WoredaCivilMarriageNewRoute
}

const WoredaCivilRouteChildren: WoredaCivilRouteChildren = {
  WoredaCivilEventIdRoute: WoredaCivilEventIdRoute,
  WoredaCivilIndexRoute: WoredaCivilIndexRoute,
  WoredaCivilBirthNewRoute: WoredaCivilBirthNewRoute,
  WoredaCivilDeathNewRoute: WoredaCivilDeathNewRoute,
  WoredaCivilDivorceNewRoute: WoredaCivilDivorceNewRoute,
  WoredaCivilMarriageNewRoute: WoredaCivilMarriageNewRoute,
}

const WoredaCivilRouteWithChildren = WoredaCivilRoute._addFileChildren(
  WoredaCivilRouteChildren,
)

interface WoredaCredentialsRouteChildren {
  WoredaCredentialsNewRoute: typeof WoredaCredentialsNewRoute
  WoredaCredentialsVerifyRoute: typeof WoredaCredentialsVerifyRoute
  WoredaCredentialsIndexRoute: typeof WoredaCredentialsIndexRoute
  WoredaCredentialsRequestIdPrintRoute: typeof WoredaCredentialsRequestIdPrintRoute
  WoredaCredentialsRequestIdIndexRoute: typeof WoredaCredentialsRequestIdIndexRoute
}

const WoredaCredentialsRouteChildren: WoredaCredentialsRouteChildren = {
  WoredaCredentialsNewRoute: WoredaCredentialsNewRoute,
  WoredaCredentialsVerifyRoute: WoredaCredentialsVerifyRoute,
  WoredaCredentialsIndexRoute: WoredaCredentialsIndexRoute,
  WoredaCredentialsRequestIdPrintRoute: WoredaCredentialsRequestIdPrintRoute,
  WoredaCredentialsRequestIdIndexRoute: WoredaCredentialsRequestIdIndexRoute,
}

const WoredaCredentialsRouteWithChildren =
  WoredaCredentialsRoute._addFileChildren(WoredaCredentialsRouteChildren)

interface WoredaHouseholdsRouteChildren {
  WoredaHouseholdsNewRoute: typeof WoredaHouseholdsNewRoute
  WoredaHouseholdsIndexRoute: typeof WoredaHouseholdsIndexRoute
  WoredaHouseholdsHouseholdIdEditRoute: typeof WoredaHouseholdsHouseholdIdEditRoute
  WoredaHouseholdsHouseholdIdIndexRoute: typeof WoredaHouseholdsHouseholdIdIndexRoute
}

const WoredaHouseholdsRouteChildren: WoredaHouseholdsRouteChildren = {
  WoredaHouseholdsNewRoute: WoredaHouseholdsNewRoute,
  WoredaHouseholdsIndexRoute: WoredaHouseholdsIndexRoute,
  WoredaHouseholdsHouseholdIdEditRoute: WoredaHouseholdsHouseholdIdEditRoute,
  WoredaHouseholdsHouseholdIdIndexRoute: WoredaHouseholdsHouseholdIdIndexRoute,
}

const WoredaHouseholdsRouteWithChildren =
  WoredaHouseholdsRoute._addFileChildren(WoredaHouseholdsRouteChildren)

interface WoredaResidentsRouteChildren {
  WoredaResidentsNewRoute: typeof WoredaResidentsNewRoute
  WoredaResidentsIndexRoute: typeof WoredaResidentsIndexRoute
  WoredaResidentsResidentIdEditRoute: typeof WoredaResidentsResidentIdEditRoute
  WoredaResidentsResidentIdIndexRoute: typeof WoredaResidentsResidentIdIndexRoute
}

const WoredaResidentsRouteChildren: WoredaResidentsRouteChildren = {
  WoredaResidentsNewRoute: WoredaResidentsNewRoute,
  WoredaResidentsIndexRoute: WoredaResidentsIndexRoute,
  WoredaResidentsResidentIdEditRoute: WoredaResidentsResidentIdEditRoute,
  WoredaResidentsResidentIdIndexRoute: WoredaResidentsResidentIdIndexRoute,
}

const WoredaResidentsRouteWithChildren = WoredaResidentsRoute._addFileChildren(
  WoredaResidentsRouteChildren,
)

interface WoredaRevenueRouteChildren {
  WoredaRevenueIndexRoute: typeof WoredaRevenueIndexRoute
  WoredaRevenuePaymentIdReceiptRoute: typeof WoredaRevenuePaymentIdReceiptRoute
}

const WoredaRevenueRouteChildren: WoredaRevenueRouteChildren = {
  WoredaRevenueIndexRoute: WoredaRevenueIndexRoute,
  WoredaRevenuePaymentIdReceiptRoute: WoredaRevenuePaymentIdReceiptRoute,
}

const WoredaRevenueRouteWithChildren = WoredaRevenueRoute._addFileChildren(
  WoredaRevenueRouteChildren,
)

interface WoredaServicesRouteChildren {
  WoredaServicesNewRoute: typeof WoredaServicesNewRoute
  WoredaServicesIndexRoute: typeof WoredaServicesIndexRoute
  WoredaServicesRequestIdPrintRoute: typeof WoredaServicesRequestIdPrintRoute
  WoredaServicesRequestIdIndexRoute: typeof WoredaServicesRequestIdIndexRoute
}

const WoredaServicesRouteChildren: WoredaServicesRouteChildren = {
  WoredaServicesNewRoute: WoredaServicesNewRoute,
  WoredaServicesIndexRoute: WoredaServicesIndexRoute,
  WoredaServicesRequestIdPrintRoute: WoredaServicesRequestIdPrintRoute,
  WoredaServicesRequestIdIndexRoute: WoredaServicesRequestIdIndexRoute,
}

const WoredaServicesRouteWithChildren = WoredaServicesRoute._addFileChildren(
  WoredaServicesRouteChildren,
)

interface WoredaRouteChildren {
  WoredaApprovalsRoute: typeof WoredaApprovalsRoute
  WoredaAuditRoute: typeof WoredaAuditRoute
  WoredaCivilRoute: typeof WoredaCivilRouteWithChildren
  WoredaComplaintsRoute: typeof WoredaComplaintsRoute
  WoredaCredentialsRoute: typeof WoredaCredentialsRouteWithChildren
  WoredaDashboardRoute: typeof WoredaDashboardRoute
  WoredaHouseholdsRoute: typeof WoredaHouseholdsRouteWithChildren
  WoredaReportsRoute: typeof WoredaReportsRoute
  WoredaResidentsRoute: typeof WoredaResidentsRouteWithChildren
  WoredaRevenueRoute: typeof WoredaRevenueRouteWithChildren
  WoredaServicesRoute: typeof WoredaServicesRouteWithChildren
  WoredaSettingsRoute: typeof WoredaSettingsRoute
  WoredaRentalHousesNewRoute: typeof WoredaRentalHousesNewRoute
  WoredaRentalHousesIndexRoute: typeof WoredaRentalHousesIndexRoute
  WoredaRentalHousesHouseIdEditRoute: typeof WoredaRentalHousesHouseIdEditRoute
  WoredaRentalHousesOccupantsNewRoute: typeof WoredaRentalHousesOccupantsNewRoute
  WoredaRentalHousesHouseIdIndexRoute: typeof WoredaRentalHousesHouseIdIndexRoute
  WoredaRentalHousesRequestsIndexRoute: typeof WoredaRentalHousesRequestsIndexRoute
  WoredaRentalHousesRequestsRequestIdIndexRoute: typeof WoredaRentalHousesRequestsRequestIdIndexRoute
}

const WoredaRouteChildren: WoredaRouteChildren = {
  WoredaApprovalsRoute: WoredaApprovalsRoute,
  WoredaAuditRoute: WoredaAuditRoute,
  WoredaCivilRoute: WoredaCivilRouteWithChildren,
  WoredaComplaintsRoute: WoredaComplaintsRoute,
  WoredaCredentialsRoute: WoredaCredentialsRouteWithChildren,
  WoredaDashboardRoute: WoredaDashboardRoute,
  WoredaHouseholdsRoute: WoredaHouseholdsRouteWithChildren,
  WoredaReportsRoute: WoredaReportsRoute,
  WoredaResidentsRoute: WoredaResidentsRouteWithChildren,
  WoredaRevenueRoute: WoredaRevenueRouteWithChildren,
  WoredaServicesRoute: WoredaServicesRouteWithChildren,
  WoredaSettingsRoute: WoredaSettingsRoute,
  WoredaRentalHousesNewRoute: WoredaRentalHousesNewRoute,
  WoredaRentalHousesIndexRoute: WoredaRentalHousesIndexRoute,
  WoredaRentalHousesHouseIdEditRoute: WoredaRentalHousesHouseIdEditRoute,
  WoredaRentalHousesOccupantsNewRoute: WoredaRentalHousesOccupantsNewRoute,
  WoredaRentalHousesHouseIdIndexRoute: WoredaRentalHousesHouseIdIndexRoute,
  WoredaRentalHousesRequestsIndexRoute: WoredaRentalHousesRequestsIndexRoute,
  WoredaRentalHousesRequestsRequestIdIndexRoute:
    WoredaRentalHousesRequestsRequestIdIndexRoute,
}

const WoredaRouteWithChildren =
  WoredaRoute._addFileChildren(WoredaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  WoredaRoute: WoredaRouteWithChildren,
  VTokenRoute: VTokenRoute,
  VerifyLetterTokenRoute: VerifyLetterTokenRoute,
  VerifyReceiptTokenRoute: VerifyReceiptTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
